import { Router, type IRouter } from "express";
import healthRouter from "./health";
import countriesRouter from "./countries";
import conflictsRouter from "./conflicts";
import committeesRouter from "./committees";
import resolutionsRouter from "./resolutions";
import alliancesRouter from "./alliances";
import intelligenceRouter from "./intelligence";
import delegatesRouter from "./delegates";
import dashboardRouter from "./dashboard";
import leadersRouter from "./leaders";
import statementsRouter from "./statements";
import parliamentaryRouter from "./parliamentary";
import legislationRouter from "./legislation";
import criminalCasesRouter from "./criminal_cases";
import interpolRouter from "./interpol";
import icjRouter from "./icj";
import treatiesRouter from "./treaties";
import mediaEventsRouter from "./media_events";
import countryIntelRouter from "./country_intel";
import liveFeedRouter from "./live_feed";
import economicsRouter from "./economics";
import searchRouter from "./search";
import entityGraphRouter from "./entity_graph";
import cyberIntelRouter from "./cyber_intel";
import nuclearProgramsRouter from "./nuclear_programs";
import operationsTimelineRouter from "./operations_timeline";
import aiAnalystRouter from "./ai_analyst";
import militaryActivitiesRouter from "./military_activities";

const router: IRouter = Router();

router.use(healthRouter);
router.use(countriesRouter);
router.use(conflictsRouter);
router.use(committeesRouter);
router.use(resolutionsRouter);
router.use(alliancesRouter);
router.use(intelligenceRouter);
router.use(delegatesRouter);
router.use(dashboardRouter);
router.use(leadersRouter);
router.use(statementsRouter);
router.use(parliamentaryRouter);
router.use(legislationRouter);
router.use(criminalCasesRouter);
router.use(interpolRouter);
router.use(icjRouter);
router.use(treatiesRouter);
router.use(mediaEventsRouter);
router.use(countryIntelRouter);
router.use(liveFeedRouter);
router.use(economicsRouter);
router.use(searchRouter);
router.use(entityGraphRouter);
router.use(cyberIntelRouter);
router.use(nuclearProgramsRouter);
router.use(operationsTimelineRouter);
router.use(aiAnalystRouter);
router.use(militaryActivitiesRouter);

export default router;
