import { db } from "./index";
import {
  worldLeadersTable,
  leaderStatementsTable,
  parliamentaryTable,
  legislationTable,
  criminalCasesTable,
  interpolTable,
  icjTable,
  treatiesTable,
  mediaEventsTable,
} from "./schema";

async function seedExtended() {
  console.log("Seeding extended data...");

  // ── WORLD LEADERS ────────────────────────────────────────────────────────
  await db.delete(worldLeadersTable);
  const leaders = await db.insert(worldLeadersTable).values(([
    {
      name: "Donald J. Trump",
      country: "United States",
      countryCode: "US",
      position: "President",
      party: "Republican",
      ideology: "National Populism, America First",
      bornDate: "1946-06-14",
      nationality: "American",
      education: "Wharton School of Business, University of Pennsylvania (B.S. Economics, 1968)",
      background: "Real estate mogul, television personality, and 45th/47th President of the United States. Built a multi-billion dollar empire including Trump Tower, Trump Hotels, and Mar-a-Lago. Became the first president in US history to be elected twice non-consecutively. Has faced unprecedented legal battles including two impeachments and multiple federal indictments, all of which were ultimately dismissed or resolved. Architect of major tax reform (2017 Tax Cuts and Jobs Act), 'Operation Warp Speed' vaccine development, and the Abraham Accords Middle East peace normalization agreements.",
      previousRoles: ["45th President of the United States (2017–2021)", "Chairman, The Trump Organization", "Executive Producer, The Apprentice"],
      netWorth: "$6.5 billion",
      twitterHandle: "@realDonaldTrump",
      approvalRating: 47.3,
      isCurrentlyInPower: true,
      notableAchievements: ["Abraham Accords (2020)", "Operation Warp Speed COVID-19 vaccine", "Tax Cuts and Jobs Act 2017", "US-China Phase 1 Trade Deal", "First president elected non-consecutively since Grover Cleveland"],
      controversies: ["January 6 Capitol riot (2021)", "Two impeachments (2019, 2021)", "New York hush money trial conviction", "Federal classified documents case", "Georgia election interference charges"],
      currentLocation: "Washington D.C. / Mar-a-Lago, Florida",
      recentTravel: ["Riyadh, Saudi Arabia", "Rome, Italy (Pope Francis meeting)", "Paris, France (Macron bilateral)", "Ottawa, Canada (Trade Summit)"],
    },
    {
      name: "Barack Obama",
      country: "United States",
      countryCode: "US",
      position: "Former President",
      party: "Democratic",
      ideology: "Progressive Liberalism, Multilateralism",
      bornDate: "1961-08-04",
      nationality: "American",
      education: "Columbia University (B.A. Political Science, 1983); Harvard Law School (J.D., 1991, President of Harvard Law Review)",
      background: "44th President of the United States (2009–2017), the first African-American to hold the office. Prior to the presidency served as Illinois State Senator and US Senator from Illinois. Nobel Peace Prize laureate (2009). Oversaw the economic recovery from the 2008 financial crisis, the passage of the Affordable Care Act, authorization of the raid that killed Osama bin Laden (2011), the Iran Nuclear Deal (JCPOA), and the Paris Climate Agreement. Since leaving office, active in Democratic party politics, podcasting, and Netflix documentary production.",
      previousRoles: ["44th President of the United States (2009–2017)", "U.S. Senator, Illinois (2005–2008)", "Illinois State Senator (1997–2004)"],
      netWorth: "$70 million",
      twitterHandle: "@BarackObama",
      approvalRating: 63.0,
      isCurrentlyInPower: false,
      notableAchievements: ["Affordable Care Act (Obamacare)", "Dodd-Frank Financial Reform", "Paris Climate Agreement", "Iran Nuclear Deal (JCPOA)", "Nobel Peace Prize (2009)", "Authorization of Operation Neptune Spear (bin Laden raid)"],
      controversies: ["PRISM NSA mass surveillance revelations (Snowden, 2013)", "Libya intervention aftermath", "Drone strike civilian casualties", "Deportation record ('Deporter-in-Chief')", "Guantanamo Bay still open at end of presidency"],
      currentLocation: "Washington D.C. / Martha's Vineyard",
      recentTravel: ["Chicago, Illinois (Obama Presidential Center opening)", "Berlin, Germany", "Johannesburg, South Africa"],
    },
    {
      name: "Elon Musk",
      country: "United States",
      countryCode: "US",
      position: "Chief of DOGE / Tech Billionaire",
      party: "Independent (Republican-aligned)",
      ideology: "Techno-libertarianism, Free Speech Absolutism",
      bornDate: "1971-06-28",
      nationality: "South African-American",
      education: "University of Pretoria; Queen's University; University of Pennsylvania (B.S. Economics, B.A. Physics); dropped out of Stanford PhD after 2 days",
      background: "World's wealthiest individual (net worth ~$350B). Co-founder of PayPal, founder and CEO of SpaceX, Tesla CEO, owner of X (formerly Twitter), founder of The Boring Company, co-founder of OpenAI (departed), founder of xAI. In 2025, appointed by President Trump to lead the Department of Government Efficiency (DOGE), tasked with cutting $2 trillion in federal spending. Controversial for mass layoffs at Twitter/X, public spats with world leaders, and increasingly political social media presence.",
      previousRoles: ["Co-founder, PayPal", "Co-founder, OpenAI (departed 2018)", "Chair, Tesla Board (resigned 2018)"],
      netWorth: "~$350 billion",
      twitterHandle: "@elonmusk",
      approvalRating: 41.0,
      isCurrentlyInPower: true,
      notableAchievements: ["Starlink global satellite internet", "SpaceX reusable rockets (Falcon 9, Starship)", "Tesla electric vehicle mass market adoption", "Acquisition of Twitter/X ($44B, 2022)", "Leading DOGE federal efficiency initiative"],
      controversies: ["DOGE mass federal layoffs", "Twitter/X content moderation controversies", "SEC Tesla tweet fines", "Alleged drug use (WSJ report)", "Interference in German and UK elections via X", "xAI Grok chatbot controversies"],
      currentLocation: "Washington D.C. / Austin, Texas",
      recentTravel: ["Berlin, Germany (Tesla Gigafactory)", "Starbase, Texas", "Riyadh, Saudi Arabia (tech summit)", "London, UK"],
    },
    {
      name: "Vladimir Putin",
      country: "Russia",
      countryCode: "RU",
      position: "President",
      party: "United Russia",
      ideology: "Russian Nationalism, Eurasianism, Neo-imperialism",
      bornDate: "1952-10-07",
      nationality: "Russian",
      education: "Leningrad State University (Law Degree, 1975); Candidate of Economic Sciences (PhD equivalent, 1997) — degree disputed as plagiarized",
      background: "Former KGB intelligence officer who rose to become Russia's dominant political figure since 1999. Has served as President (2000–2008, 2012–present) and Prime Minister (2008–2012). Orchestrated Russia's military interventions in Chechnya, Georgia (2008), annexation of Crimea (2014), and the full-scale invasion of Ukraine (February 24, 2022). Subject to ICC arrest warrant (2023) for war crimes related to deportation of Ukrainian children. Has consolidated near-total political control, eliminating opposition including the imprisonment of Alexei Navalny (who died in prison in 2024).",
      previousRoles: ["Prime Minister of Russia (1999–2000, 2008–2012)", "Director, Federal Security Service FSB (1998–1999)", "KGB Officer (1975–1991)", "Deputy Mayor of St. Petersburg (1994–1996)"],
      netWorth: "Estimated $200 billion (hidden assets) — officially declares minimal",
      twitterHandle: null,
      approvalRating: 75.0,
      isCurrentlyInPower: true,
      notableAchievements: ["Economic growth through 2000s oil boom", "Restored Russian global power projection", "BRICS expansion leadership", "Modernization of Russian military"],
      controversies: ["Full-scale invasion of Ukraine (2022-present)", "ICC arrest warrant for war crimes (2023)", "Annexation of Crimea (2014)", "Poisonings of Sergei Skripal, Alexander Litvinenko", "Death of Alexei Navalny in prison (2024)", "Suppression of all political opposition"],
      currentLocation: "Moscow, Russia (Kremlin / Novo-Ogaryovo residence)",
      recentTravel: ["Beijing, China (Xi Jinping summit)", "Pyongyang, North Korea (Kim Jong-un alliance)", "Abu Dhabi, UAE", "Minsk, Belarus"],
    },
    {
      name: "Xi Jinping",
      country: "China",
      countryCode: "CN",
      position: "General Secretary / President",
      party: "Chinese Communist Party",
      ideology: "Xi Jinping Thought, Chinese Nationalism, Socialism with Chinese Characteristics",
      bornDate: "1953-06-15",
      nationality: "Chinese",
      education: "Tsinghua University (Chemical Engineering, 1975; Law PhD, 2002)",
      background: "China's most powerful leader since Mao Zedong. Has served as General Secretary of the CCP since 2012 and President since 2013. Eliminated the two-term presidential limit in 2018, enabling indefinite rule. Overseen China's rise to become the world's second largest economy, massive infrastructure investment via Belt and Road Initiative, aggressive territorial expansion in the South China Sea, and military build-up toward potential Taiwan reunification. Cracked down on Hong Kong's autonomy, Uyghur Muslim minority in Xinjiang, and political dissent.",
      previousRoles: ["Vice President of China (2008–2013)", "Governor of Fujian Province", "Governor of Zhejiang Province", "Party Secretary of Shanghai"],
      netWorth: "Officially minimal; family linked to hundreds of millions in assets",
      twitterHandle: null,
      approvalRating: 82.0,
      isCurrentlyInPower: true,
      notableAchievements: ["Belt and Road Initiative (150+ countries)", "Poverty alleviation program (lifted 800M from poverty claim)", "Made-in-China 2025 tech strategy", "Digital Yuan / CBDC implementation", "BRICS+ expansion"],
      controversies: ["Uyghur genocide/mass detention in Xinjiang", "Hong Kong crackdown (2019-2020)", "COVID-19 origins cover-up allegations", "South China Sea militarization", "Taiwan military threats", "Espionage operations against Western democracies"],
      currentLocation: "Beijing, China (Zhongnanhai)",
      recentTravel: ["Moscow, Russia (Putin summit)", "Riyadh, Saudi Arabia", "Paris, France (Macron trilateral)", "Budapest, Hungary"],
    },
    {
      name: "Narendra Modi",
      country: "India",
      countryCode: "IN",
      position: "Prime Minister",
      party: "Bharatiya Janata Party (BJP)",
      ideology: "Hindu Nationalism (Hindutva), Economic Nationalism",
      bornDate: "1950-09-17",
      nationality: "Indian",
      education: "Gujarat University (Political Science BA, 1983); Gujarat University (Political Science MA, 1983)",
      background: "14th Prime Minister of India, in office since 2014. Former Chief Minister of Gujarat (2001–2014). Member of the Rashtriya Swayamsevak Sangh (RSS) since childhood. Led BJP to historic parliamentary majorities in 2014 and 2019, but lost outright majority in 2024 and continues in coalition. Known for demonetization (2016), GST reform, Aadhaar digital identity system, and Make in India initiative. India became the world's most populous nation (surpassing China) and 5th largest economy under his tenure.",
      previousRoles: ["Chief Minister of Gujarat (2001–2014)", "General Secretary, BJP", "RSS Pracharak"],
      netWorth: "Officially minimal (~$280,000 declared assets)",
      twitterHandle: "@narendramodi",
      approvalRating: 68.0,
      isCurrentlyInPower: true,
      notableAchievements: ["India became 5th largest economy", "UPI digital payments revolution", "Chandrayaan-3 Moon landing (2023)", "India G20 Presidency (2023)", "Aadhaar biometric ID system"],
      controversies: ["2002 Gujarat riots (acquitted)", "CAA/NRC citizenship law protests", "Kashmir lockdown/Article 370 revocation (2019)", "Farmer protests (2020-2021)", "Press freedom decline", "Electoral bond scheme controversy"],
      currentLocation: "New Delhi, India (7 Lok Kalyan Marg)",
      recentTravel: ["Washington D.C. (Trump bilateral)", "Moscow, Russia (Modi-Putin summit)", "Kyiv, Ukraine (first Indian PM visit)", "Singapore, Malaysia"],
    },
    {
      name: "Emmanuel Macron",
      country: "France",
      countryCode: "FR",
      position: "President",
      party: "Renaissance (En Marche!)",
      ideology: "Liberal Centrism, Pro-European Federalism",
      bornDate: "1977-12-21",
      nationality: "French",
      education: "Sciences Po Paris; École Nationale d'Administration (ENA)",
      background: "Youngest President in French history, elected in 2017 at age 39. Former investment banker at Rothschild & Co and Economy Minister under François Hollande. Re-elected in 2022 defeating Marine Le Pen but lost parliamentary majority. A committed pro-European federalist who has pushed for greater EU strategic autonomy from the United States. Faced the Yellow Vest protests (2018-2019), COVID-19 pandemic, and significant domestic political turbulence including failed no-confidence votes.",
      previousRoles: ["Minister of Economy and Finance, France (2014–2016)", "Deputy Secretary-General of the Élysée", "Investment Banker, Rothschild & Co"],
      netWorth: "~$1 million (declared)",
      twitterHandle: "@EmmanuelMacron",
      approvalRating: 29.0,
      isCurrentlyInPower: true,
      notableAchievements: ["European Strategic Autonomy doctrine", "EU recovery fund (€750B, post-COVID)", "French nuclear deterrence modernization", "Africa CFA franc reform"],
      controversies: ["Pension reform protests (2023)", "Yellow Vest movement suppression", "Controversial meeting with Putin (2022)", "New Caledonia independence referendum handling", "Dissolution of National Assembly (2024) — backfired"],
      currentLocation: "Paris, France (Élysée Palace)",
      recentTravel: ["Warsaw, Poland (NATO support)", "Kyiv, Ukraine", "Beijing, China", "Washington D.C."],
    },
    {
      name: "Kim Jong-un",
      country: "North Korea",
      countryCode: "KP",
      position: "Supreme Leader",
      party: "Korean Workers' Party",
      ideology: "Juche, Songun (Military-First Policy), Neo-Stalinism",
      bornDate: "1984-01-08",
      nationality: "North Korean",
      education: "Kim Il-sung University (Physics); University of Bern, Switzerland (under pseudonym)",
      background: "Supreme Leader of North Korea since 2011 following the death of his father Kim Jong-il. Third-generation dynastic ruler of the DPRK. Has massively accelerated North Korea's nuclear weapons and ICBM programs, conducting 6 nuclear tests (including claimed hydrogen bomb). Executed his uncle Jang Song-thaek (2013) and is believed to have ordered assassination of his half-brother Kim Jong-nam (2017, Kuala Lumpur airport). Held unprecedented summit with US President Trump (Singapore, 2018; Hanoi, 2019) but denuclearization talks collapsed. In 2024 signed strategic partnership treaty with Russia, deploying North Korean troops to fight in Ukraine.",
      previousRoles: ["Supreme Commander, Korean People's Army", "First Secretary, Korean Workers' Party"],
      netWorth: "Unknown — controls entire state",
      twitterHandle: null,
      approvalRating: null,
      isCurrentlyInPower: true,
      notableAchievements: ["ICBM capable of reaching US mainland", "Hydrogen bomb test (2017 claim)", "Historic Trump-Kim summits (2018-2019)", "Russia strategic partnership (2024)"],
      controversies: ["Execution of uncle Jang Song-thaek", "Assassination of Kim Jong-nam (2017)", "UN concentration camps (Yodok, Chongjin)", "Mass starvation/famine", "Nuclear provocations", "Deployment of troops to Russia-Ukraine war"],
      currentLocation: "Pyongyang, North Korea",
      recentTravel: ["Moscow, Russia (Putin meeting)"],
    },
    {
      name: "Mohammed bin Salman",
      country: "Saudi Arabia",
      countryCode: "SA",
      position: "Crown Prince / Prime Minister",
      party: "Al Saud Royal Family",
      ideology: "Vision 2030 Modernization, Arab Nationalism",
      bornDate: "1985-08-31",
      nationality: "Saudi",
      education: "King Saud University (Law degree)",
      background: "Crown Prince and Prime Minister of Saudi Arabia, de facto ruler since 2017. Known as MBS. Launched Vision 2030 to diversify the Saudi economy away from oil, including mega-projects like NEOM, the $500B futuristic city. Oversaw opening of Saudi society (allowing women to drive, entertainment venues). However, oversaw the murder and dismemberment of journalist Jamal Khashoggi at the Saudi consulate in Istanbul (2018), which the CIA concluded was ordered by MBS. Prosecuted the devastating Yemen war that has caused over 400,000 deaths.",
      previousRoles: ["Minister of Defense (2015–present)", "Governor of Riyadh (2013-2015)"],
      netWorth: "~$7 billion (official); controls $700B+ sovereign wealth fund",
      twitterHandle: null,
      approvalRating: 78.0,
      isCurrentlyInPower: true,
      notableAchievements: ["Vision 2030 economic reform plan", "NEOM mega-city project", "Saudi-Israel normalization talks", "Women allowed to drive (2018)", "OPEC+ production management"],
      controversies: ["Murder of Jamal Khashoggi (2018)", "Yemen war (400,000+ deaths)", "Detention of rivals in Ritz-Carlton (2017)", "Qatar blockade (2017-2021)", "Crackdown on dissidents"],
      currentLocation: "Riyadh, Saudi Arabia",
      recentTravel: ["Beijing, China", "Washington D.C.", "Paris, France", "Tokyo, Japan"],
    },
    {
      name: "Volodymyr Zelensky",
      country: "Ukraine",
      countryCode: "UA",
      position: "President",
      party: "Servant of the People",
      ideology: "Ukrainian Nationalism, Liberal Democracy, Euro-Atlanticism",
      bornDate: "1978-01-25",
      nationality: "Ukrainian",
      education: "Kryvyi Rih Institute of Economics (Law degree, 2000)",
      background: "Former comedian and actor who played the President of Ukraine in the TV series 'Servant of the People' before running for actual president in 2019, winning with 73% of the vote. Became a globally recognized wartime leader after Russia's full-scale invasion in February 2022, refusing evacuation and famously saying 'I need ammunition, not a ride.' Has addressed nearly every major world parliament and democratic institution, securing hundreds of billions in military and financial aid. Named TIME Person of the Year 2022. Has navigated tensions with Trump administration over peace negotiations.",
      previousRoles: ["Actor and Comedian", "Creator/Star, 'Servant of the People' TV series", "Founder, Kvartal 95 production studio"],
      netWorth: "~$20-30 million (pre-war estimates)",
      twitterHandle: "@ZelenskyyUa",
      approvalRating: 57.0,
      isCurrentlyInPower: true,
      notableAchievements: ["Led Ukrainian resistance to Russian invasion", "Secured $200B+ in international military aid", "TIME Person of the Year (2022)", "EU candidate status for Ukraine (2022)", "Liberation of Kherson, Kharkiv regions"],
      controversies: ["Martial law extension/elections suspended", "Tensions with Trump over peace terms", "Corruption allegations within Ukrainian government", "Mobilization law controversies", "Dispute with Zaluzhnyi (fired military chief)"],
      currentLocation: "Kyiv, Ukraine",
      recentTravel: ["Washington D.C. (Trump-Zelensky meeting)", "Paris, France", "Berlin, Germany", "London, UK", "Brussels, NATO HQ"],
    },
    {
      name: "Benjamin Netanyahu",
      country: "Israel",
      countryCode: "IL",
      position: "Prime Minister",
      party: "Likud",
      ideology: "Right-wing Nationalism, Security-First Zionism",
      bornDate: "1949-10-21",
      nationality: "Israeli",
      education: "MIT (S.B. Architecture, 1975; S.M. Management, 1977)",
      background: "Israel's longest-serving Prime Minister, in office 1996-1999 and 2009-2021, and again since December 2022. Has guided Israel through the October 7, 2023 Hamas terrorist attacks (1,200 Israelis killed, 251 taken hostage) and the subsequent Gaza war. Faces ICC arrest warrant (November 2024) for war crimes and crimes against humanity in Gaza. On trial domestically for corruption (bribery, fraud, breach of trust). His judicial overhaul plan triggered the largest protest movement in Israeli history.",
      previousRoles: ["Foreign Minister (2002-2003)", "Finance Minister (2003-2005)", "UN Ambassador (1984-1988)", "Deputy Chief of Mission, Washington"],
      netWorth: "~$14 million (declared)",
      twitterHandle: "@netanyahu",
      approvalRating: 29.0,
      isCurrentlyInPower: true,
      notableAchievements: ["Abraham Accords framework", "Iron Dome missile defense expansion", "Iran nuclear program disruption operations", "Israeli tech/startup nation development"],
      controversies: ["ICC arrest warrant for war crimes (2024)", "Gaza war civilian casualties (47,000+)", "October 7 intelligence failure", "Corruption trial (ongoing)", "Judicial overhaul protests", "Settlement expansion in West Bank"],
      currentLocation: "Jerusalem, Israel",
      recentTravel: ["Washington D.C. (Congress address)", "New York (UN General Assembly)"],
    },
    {
      name: "Recep Tayyip Erdogan",
      country: "Turkey",
      countryCode: "TR",
      position: "President",
      party: "AKP (Justice and Development Party)",
      ideology: "Islamic Conservatism, Neo-Ottoman Nationalism, Authoritarianism",
      bornDate: "1954-02-26",
      nationality: "Turkish",
      education: "Marmara University (Business Administration)",
      background: "President of Turkey since 2014, previously Prime Minister 2003-2014. Transformed Turkey from parliamentary to presidential system via 2017 referendum. Has pursued aggressive foreign policy including military operations in Syria, Libya, Nagorno-Karabakh, and Northern Iraq. Leveraged Turkey's NATO membership as a bargaining chip, blocking Sweden and Finland's NATO bids before eventually accepting. Faces criticism for democratic backsliding, press freedom decline, and jailing political opponents including Kurdish leaders.",
      previousRoles: ["Prime Minister of Turkey (2003–2014)", "Mayor of Istanbul (1994–1998)", "Member of Parliament"],
      netWorth: "Officially minimal; family linked to billions",
      twitterHandle: null,
      approvalRating: 43.0,
      isCurrentlyInPower: true,
      notableAchievements: ["Turkish economic growth (2000s)", "NATO enlargement mediation (Sweden, Finland)", "Grain corridor deal for Ukraine", "Istanbul Canal project", "Syrian refugee management"],
      controversies: ["2016 coup attempt aftermath (150,000+ arrested/fired)", "Kurdish repression/PKK operations", "Blocking NATO enlargement as leverage", "Press freedom and judiciary independence", "Post-earthquake response (2023) criticism", "Economic mismanagement/inflation crisis"],
      currentLocation: "Ankara, Turkey",
      recentTravel: ["Moscow, Russia", "Baku, Azerbaijan", "Doha, Qatar", "Tehran, Iran"],
    },
  ] as any)).returning();

  console.log(`Seeded ${leaders.length} world leaders`);

  // ── LEADER STATEMENTS ───────────────────────────────────────────────────
  await db.delete(leaderStatementsTable);
  const trumpId = leaders.find(l => l.name === "Donald J. Trump")!.id;
  const obamaId = leaders.find(l => l.name === "Barack Obama")!.id;
  const muskId = leaders.find(l => l.name === "Elon Musk")!.id;
  const putinId = leaders.find(l => l.name === "Vladimir Putin")!.id;
  const xiId = leaders.find(l => l.name === "Xi Jinping")!.id;
  const modiId = leaders.find(l => l.name === "Narendra Modi")!.id;
  const macronId = leaders.find(l => l.name === "Emmanuel Macron")!.id;
  const zelenskyId = leaders.find(l => l.name === "Volodymyr Zelensky")!.id;
  const netanyahuId = leaders.find(l => l.name === "Benjamin Netanyahu")!.id;
  const mbsId = leaders.find(l => l.name === "Mohammed bin Salman")!.id;

  const statements = await db.insert(leaderStatementsTable).values([
    {
      leaderId: trumpId, leaderName: "Donald J. Trump", country: "United States",
      platform: "Truth Social / X",
      content: "Just had a GREAT call with President Putin. He wants to make a deal, and so do I. The Ukraine War will end FAST! No more dying. Our military is STRONGER THAN EVER and we will MAKE AMERICA GREAT AGAIN!",
      sentiment: "positive", topic: "Ukraine War / Russia", relatedCountries: ["Russia", "Ukraine"],
      engagement: 487320, isControversial: true,
      timestamp: new Date("2026-03-28T14:30:00Z"),
    },
    {
      leaderId: trumpId, leaderName: "Donald J. Trump", country: "United States",
      platform: "Truth Social",
      content: "TARIFFS ARE WORKING! China is begging to make a deal. We will ONLY accept FAIR TRADE for American workers. The days of taking advantage of the USA are OVER! 145% tariffs stay until China comes to the table honestly.",
      sentiment: "negative", topic: "US-China Trade War", relatedCountries: ["China"],
      engagement: 312450, isControversial: true,
      timestamp: new Date("2026-04-01T09:15:00Z"),
    },
    {
      leaderId: trumpId, leaderName: "Donald J. Trump", country: "United States",
      platform: "Press Conference",
      content: "Canada should seriously consider becoming the 51st state. Think about it — lower taxes, the most powerful military in the world protecting you. It makes total sense. Prime Minister Trudeau knows it too, he's just afraid to say it publicly.",
      sentiment: "controversial", topic: "Canada Annexation", relatedCountries: ["Canada"],
      engagement: 892000, isControversial: true,
      timestamp: new Date("2026-01-15T16:00:00Z"),
    },
    {
      leaderId: muskId, leaderName: "Elon Musk", country: "United States",
      platform: "X (Twitter)",
      content: "DOGE has now identified $847 billion in wasteful federal spending. The swamp is deeper than anyone imagined. We will not stop until government works FOR the people, not against them. The bureaucracy is the enemy.",
      sentiment: "controversial", topic: "DOGE / Government Spending", relatedCountries: ["United States"],
      engagement: 1240000, isControversial: true,
      timestamp: new Date("2026-03-15T11:00:00Z"),
    },
    {
      leaderId: muskId, leaderName: "Elon Musk", country: "United States",
      platform: "X (Twitter)",
      content: "Germany's AfD is the only party that can save Germany. The other parties have destroyed the economy with green ideology and opened borders to chaos. Germans deserve better. Vote for your future.",
      sentiment: "controversial", topic: "German Politics", relatedCountries: ["Germany"],
      engagement: 2100000, isControversial: true,
      timestamp: new Date("2025-12-19T20:00:00Z"),
    },
    {
      leaderId: muskId, leaderName: "Elon Musk", country: "United States",
      platform: "X (Twitter)",
      content: "Starship will reach Mars by 2030. I have never been more confident. The first crewed mission is on schedule. Humanity will be multi-planetary in our lifetime.",
      sentiment: "positive", topic: "SpaceX / Mars Mission", relatedCountries: [],
      engagement: 3400000, isControversial: false,
      timestamp: new Date("2026-02-20T18:30:00Z"),
    },
    {
      leaderId: obamaId, leaderName: "Barack Obama", country: "United States",
      platform: "X (Twitter)",
      content: "For 250 years, American democracy has bent but never broken — because of the remarkable people who keep showing up for it. Let's keep going.",
      sentiment: "positive", topic: "American Democracy", relatedCountries: ["United States"],
      engagement: 945000, isControversial: false,
      timestamp: new Date("2026-03-04T10:00:00Z"),
    },
    {
      leaderId: obamaId, leaderName: "Barack Obama", country: "United States",
      platform: "X (Twitter)",
      content: "Gutting USAID doesn't just harm the world's most vulnerable people. It abandons America's leadership, weakens our national security, and cedes influence to China and Russia. This is a gift to our adversaries.",
      sentiment: "negative", topic: "USAID Cuts / Foreign Policy", relatedCountries: ["United States"],
      engagement: 1230000, isControversial: true,
      timestamp: new Date("2026-02-10T14:00:00Z"),
    },
    {
      leaderId: putinId, leaderName: "Vladimir Putin", country: "Russia",
      platform: "State Address (Kremlin)",
      content: "Russia has never sought war with Ukraine. We were forced to act in response to NATO's reckless expansion and the genocide against Russian-speaking populations in Donbas. We will achieve all objectives of the special military operation.",
      sentiment: "controversial", topic: "Ukraine War", relatedCountries: ["Ukraine", "NATO"],
      engagement: 520000, isControversial: true,
      timestamp: new Date("2026-02-24T09:00:00Z"),
    },
    {
      leaderId: putinId, leaderName: "Vladimir Putin", country: "Russia",
      platform: "Federal Assembly Address",
      content: "Russia has successfully tested the Burevestnik nuclear-powered cruise missile with unlimited range. Any aggressor who dares attack Russian territory will face consequences they cannot imagine. Our nuclear triad remains fully operational.",
      sentiment: "negative", topic: "Nuclear Weapons / Military", relatedCountries: [],
      engagement: 780000, isControversial: true,
      timestamp: new Date("2026-03-01T14:00:00Z"),
    },
    {
      leaderId: xiId, leaderName: "Xi Jinping", country: "China",
      platform: "NPC Address",
      content: "Taiwan's reunification with the motherland is a historical inevitability and the shared aspiration of all Chinese people. No force can stop the progress of China's great national rejuvenation. We will complete this sacred mission.",
      sentiment: "controversial", topic: "Taiwan", relatedCountries: ["Taiwan"],
      engagement: 640000, isControversial: true,
      timestamp: new Date("2026-03-05T10:00:00Z"),
    },
    {
      leaderId: xiId, leaderName: "Xi Jinping", country: "China",
      platform: "Belt and Road Forum Speech",
      content: "China's Belt and Road Initiative has brought connectivity, development and prosperity to over 150 nations. We offer an alternative to Western conditionality — investment without interference. China does not export ideology, only opportunity.",
      sentiment: "positive", topic: "Belt and Road Initiative", relatedCountries: [],
      engagement: 290000, isControversial: false,
      timestamp: new Date("2025-10-18T09:00:00Z"),
    },
    {
      leaderId: modiId, leaderName: "Narendra Modi", country: "India",
      platform: "X (Twitter)",
      content: "India's GDP has crossed $4 trillion. When I became PM, it was $2 trillion. We are now the world's 4th largest economy. Viksit Bharat by 2047 is not just a dream — it is our determined commitment. Jai Hind!",
      sentiment: "positive", topic: "India Economy", relatedCountries: ["India"],
      engagement: 567000, isControversial: false,
      timestamp: new Date("2026-02-28T08:00:00Z"),
    },
    {
      leaderId: modiId, leaderName: "Narendra Modi", country: "India",
      platform: "Parliament Address",
      content: "Operation Sindoor was India's decisive response to the Pahalgam terror attack. We have struck nine terror infrastructure sites across Pakistan and Pakistan-occupied Kashmir with precision. India will not tolerate any attack on its citizens.",
      sentiment: "controversial", topic: "India-Pakistan / Operation Sindoor", relatedCountries: ["Pakistan"],
      engagement: 2300000, isControversial: true,
      timestamp: new Date("2025-05-07T22:00:00Z"),
    },
    {
      leaderId: macronId, leaderName: "Emmanuel Macron", country: "France",
      platform: "Press Conference (Élysée)",
      content: "Europe cannot depend on the United States for its security indefinitely. We must build genuine European strategic autonomy. France is prepared to discuss extending its nuclear deterrence to European partners. This is not a provocation, it is responsibility.",
      sentiment: "controversial", topic: "European Strategic Autonomy", relatedCountries: ["Europe", "NATO"],
      engagement: 298000, isControversial: true,
      timestamp: new Date("2026-03-12T15:00:00Z"),
    },
    {
      leaderId: zelenskyId, leaderName: "Volodymyr Zelensky", country: "Ukraine",
      platform: "Telegram",
      content: "Ukraine will never accept a peace that legitimizes Russia's occupation of our land. Crimea is Ukraine. Donbas is Ukraine. We fight not just for our borders — we fight for the principle that borders cannot be changed by force. That principle protects every nation.",
      sentiment: "controversial", topic: "Ukraine War / Peace Talks", relatedCountries: ["Russia"],
      engagement: 870000, isControversial: false,
      timestamp: new Date("2026-04-02T18:00:00Z"),
    },
    {
      leaderId: zelenskyId, leaderName: "Volodymyr Zelensky", country: "Ukraine",
      platform: "X (Twitter)",
      content: "Another Russian missile attack on Kharkiv. A residential block. Children's hospital. This is what Russia calls a 'Special Military Operation.' The world must see this. Where is the ceasefire Putin claims to support?",
      sentiment: "negative", topic: "Russian Attacks on Ukraine", relatedCountries: ["Russia"],
      engagement: 1340000, isControversial: false,
      timestamp: new Date("2026-03-30T07:00:00Z"),
    },
    {
      leaderId: netanyahuId, leaderName: "Benjamin Netanyahu", country: "Israel",
      platform: "Press Conference",
      content: "The ICC's arrest warrant against me is an obscene moral inversion. While Hamas butchers babies and rapes women, the court targets the leader of a democracy defending itself. This court has no legitimacy. Israel will not be deterred.",
      sentiment: "negative", topic: "ICC Arrest Warrant", relatedCountries: [],
      engagement: 456000, isControversial: true,
      timestamp: new Date("2024-11-22T12:00:00Z"),
    },
    {
      leaderId: mbsId, leaderName: "Mohammed bin Salman", country: "Saudi Arabia",
      platform: "Future Investment Initiative Speech",
      content: "NEOM is not just a city — it is humanity's next chapter. The Line will house 9 million people with zero cars, zero streets, zero carbon emissions. We are building the most ambitious human project in history.",
      sentiment: "positive", topic: "NEOM / Vision 2030", relatedCountries: ["Saudi Arabia"],
      engagement: 234000, isControversial: false,
      timestamp: new Date("2025-10-22T10:00:00Z"),
    },
  ]).returning();

  console.log(`Seeded ${statements.length} leader statements`);

  // ── PARLIAMENTARY DISCUSSIONS ────────────────────────────────────────────
  await db.delete(parliamentaryTable);
  const parliamentary = await db.insert(parliamentaryTable).values([
    {
      country: "United States", countryCode: "US", chamber: "Senate",
      topic: "RESTRICT Act — Banning TikTok and Chinese Tech Applications",
      description: "Senate debate on legislation that would grant the executive branch power to ban or restrict technology from adversary nations including China. TikTok with 170 million US users at center of debate. National security proponents argue CCP could access US user data; free speech advocates argue ban is unconstitutional.",
      status: "debate", date: "2026-03-18",
      keyPoints: ["National security vs First Amendment tensions", "ByteDance divestiture option still on table", "Oracle bid for US TikTok operations", "Youth vote implications for 2026 midterms"],
      votesFor: 54, votesAgainst: 43, abstentions: 3,
      significance: "high",
    },
    {
      country: "United States", countryCode: "US", chamber: "House of Representatives",
      topic: "Border Security and Mass Deportation Funding Bill",
      description: "Emergency supplemental appropriations bill providing $65 billion for border wall construction, immigration enforcement, detention facilities, and mass deportation operations. Democrats largely opposed; bill passed on party-line vote.",
      status: "voted", date: "2026-02-14",
      outcome: "Passed House 218-212, advanced to Senate",
      keyPoints: ["$65B emergency supplemental appropriation", "500 miles of additional border wall", "Expanded ICE detention capacity", "Fast-track immigration courts"],
      votesFor: 218, votesAgainst: 212, abstentions: 0,
      significance: "high",
    },
    {
      country: "United Kingdom", countryCode: "GB", chamber: "House of Commons",
      topic: "AI Safety and Regulation Bill — Second Reading",
      description: "Labour government's comprehensive AI safety legislation establishing mandatory safety assessments for frontier AI systems, new AI Safety Institute statutory powers, and liability framework for AI-caused harms. Tech industry lobbying intensely against provisions.",
      status: "debate", date: "2026-03-25",
      keyPoints: ["Mandatory frontier model safety evaluations", "AI Safety Institute statutory powers", "Compensation framework for AI harms", "Exemptions for academic research"],
      votesFor: 0, votesAgainst: 0, abstentions: 0,
      significance: "high",
    },
    {
      country: "United Kingdom", countryCode: "GB", chamber: "House of Commons",
      topic: "Rwanda Deportation Policy — Emergency Debate",
      description: "Emergency debate following the Supreme Court's ruling that the Rwanda asylum policy is unlawful. Home Office seeking revised legal framework. Cross-party divisions on how to address small boat channel crossings.",
      status: "concluded", date: "2025-11-15",
      outcome: "Policy withdrawn; new Safe Countries framework under development",
      keyPoints: ["Supreme Court ruled Rwanda policy unlawful", "140,000+ channel crossing attempts in 2025", "Tension with European Convention on Human Rights", "Deterrence vs humanitarian obligations debate"],
      votesFor: 0, votesAgainst: 0, abstentions: 0,
      significance: "high",
    },
    {
      country: "India", countryCode: "IN", chamber: "Lok Sabha",
      topic: "Waqf (Amendment) Bill 2024 — Parliamentary Debate",
      description: "Highly contentious bill amending the management of Muslim religious endowment (Waqf) properties in India. BJP government argues the bill prevents property misuse; Muslim organizations and opposition parties argue it infringes on minority religious rights.",
      status: "voted", date: "2024-08-08",
      outcome: "Passed 288-232; referred to Joint Parliamentary Committee",
      keyPoints: ["First non-Muslim member on Waqf Board", "Government audit of Waqf properties", "Opposition walkout by INDIA alliance", "Protests outside Parliament"],
      votesFor: 288, votesAgainst: 232, abstentions: 0,
      significance: "high",
    },
    {
      country: "India", countryCode: "IN", chamber: "Lok Sabha",
      topic: "One Nation One Election — Constitutional Amendment Bill",
      description: "Modi government's flagship constitutional reform to synchronize all state and national elections to be held simultaneously every 5 years. Proponents argue cost savings and policy stability; opposition argues it centralizes power and threatens federalism.",
      status: "debate", date: "2026-03-10",
      keyPoints: ["Requires 2/3 parliamentary majority", "Estimated ₹4,500 crore savings per election cycle", "15 states oppose the proposal", "JPC examining constitutional feasibility"],
      votesFor: 0, votesAgainst: 0, abstentions: 0,
      significance: "high",
    },
    {
      country: "Russia", countryCode: "RU", chamber: "State Duma",
      topic: "Strategic Partnership Treaty with North Korea — Ratification",
      description: "Ratification of the comprehensive strategic partnership treaty signed with North Korea in June 2024 in Pyongyang. Treaty includes mutual defense clause (Article 4) requiring military assistance if either party is attacked. Critics note this mirrors NATO's Article 5.",
      status: "voted", date: "2024-11-25",
      outcome: "Ratified 476-0 with 1 abstention",
      keyPoints: ["Mutual defense clause Article 4", "North Korean troops in Ukraine", "Technology transfers to DPRK", "Sanctions evasion coordination"],
      votesFor: 476, votesAgainst: 0, abstentions: 1,
      significance: "high",
    },
    {
      country: "Germany", countryCode: "DE", chamber: "Bundestag",
      topic: "Special Defence Fund (Sondervermögen) — €1 Trillion Military Rearmament",
      description: "Historic vote establishing Germany's largest-ever defence spending increase. Friedrich Merz government proposes €500B military Sondervermögen plus exemption of defence spending from debt brake, effectively allowing €1T+ investment over 10 years. Represents fundamental shift in German pacifist post-war doctrine.",
      status: "voted", date: "2025-03-18",
      outcome: "Passed 513-207. Historic reversal of post-WWII German pacifism.",
      keyPoints: ["Largest German military expansion since WWII", "Debt brake constitutional amendment", "Eurofighter, Leopard 3, F-35 procurement", "European defence integration push"],
      votesFor: 513, votesAgainst: 207, abstentions: 0,
      significance: "high",
    },
    {
      country: "France", countryCode: "FR", chamber: "National Assembly",
      topic: "Pension Reform — Raising Retirement Age to 64",
      description: "Highly contentious pension reform raising the legal retirement age from 62 to 64. Macron government pushed it through without a full parliamentary vote using Article 49.3 constitutional procedure, triggering nationwide strikes and protests. Narrowly survived two no-confidence votes.",
      status: "concluded", date: "2023-04-15",
      outcome: "Enacted via Article 49.3; no-confidence votes failed by 9 and 1 votes respectively",
      keyPoints: ["Retirement age raised from 62 to 64", "Used Article 49.3 to bypass vote", "Largest French strikes since 1968", "Macron approval rating fell to 28%"],
      votesFor: 0, votesAgainst: 0, abstentions: 0,
      significance: "high",
    },
    {
      country: "Israel", countryCode: "IL", chamber: "Knesset",
      topic: "Judicial Overhaul — Supreme Court Jurisdiction Limitation",
      description: "Netanyahu coalition's bill to drastically limit the Supreme Court's ability to strike down government decisions using 'reasonableness' standard. Critics called it a coup against Israeli democracy; supporters argued elected government should not be overridden by unelected judges. October 7 attacks froze the legislation.",
      status: "tabled", date: "2023-09-01",
      outcome: "Suspended following October 7, 2023 Hamas attacks; partially resumed in 2025",
      keyPoints: ["Elimination of 'reasonableness' standard", "Override clause proposal", "Largest protests in Israeli history (months)", "Reservists threatened to refuse service"],
      votesFor: 64, votesAgainst: 56, abstentions: 0,
      significance: "high",
    },
    {
      country: "China", countryCode: "CN", chamber: "National People's Congress",
      topic: "National Security Law Extensions — Cyber and Data Sovereignty",
      description: "NPC session passing expanded data security and national security legislation requiring all foreign companies operating in China to store Chinese citizen data on domestic servers and subject it to government inspection. Effectively codifies tech sovereignty and enables espionage on foreign corporate data.",
      status: "voted", date: "2025-09-10",
      outcome: "Passed unanimously (2,977-0)",
      keyPoints: ["Mandatory domestic data storage for all companies", "Government inspection rights on foreign firm data", "Penalties up to market exclusion", "Impacts Apple, Google, Microsoft, Tesla"],
      votesFor: 2977, votesAgainst: 0, abstentions: 0,
      significance: "high",
    },
    {
      country: "Pakistan", countryCode: "PK", chamber: "National Assembly",
      topic: "Emergency War Powers — Response to Operation Sindoor",
      description: "Emergency session following India's Operation Sindoor cross-border strikes against alleged terrorist infrastructure. Pakistani government seeking parliamentary authorization for military response options and full mobilization of armed forces. Tensions at highest level since 2001.",
      status: "ongoing", date: "2025-05-08",
      keyPoints: ["India-Pakistan crisis at 2001 levels", "Nuclear-armed states in direct conflict", "UN Security Council emergency session called", "China and US urging de-escalation"],
      votesFor: 0, votesAgainst: 0, abstentions: 0,
      significance: "high",
    },
  ]).returning();

  console.log(`Seeded ${parliamentary.length} parliamentary discussions`);

  // ── LEGISLATION ──────────────────────────────────────────────────────────
  await db.delete(legislationTable);
  const legislation = await db.insert(legislationTable).values([
    {
      country: "United States", countryCode: "US",
      title: "DOGE Accountability and Government Efficiency Act",
      description: "Legislation to formalize and expand DOGE's mandate, granting it legal authority to conduct federal agency audits, recommend mass layoffs, and eliminate programs without congressional approval. Democrats argue it unconstitutionally bypasses Congress's power of the purse.",
      status: "debate", category: "government", proposedDate: "2026-01-20",
      proposedBy: "Republican Leadership / Trump Administration",
      supportingParties: ["Republican Party"],
      opposingParties: ["Democratic Party"],
      publicOpinion: "mixed",
      impact: "Could result in elimination of up to 200,000 federal jobs and $2T in spending cuts over 10 years",
      controversyLevel: "high",
    },
    {
      country: "United States", countryCode: "US",
      title: "Alien Enemies Act Enforcement — Venezuela/Tren de Aragua",
      description: "Executive invocation of 1798 Alien Enemies Act to deport Venezuelan nationals alleged to be members of Tren de Aragua gang. Challenged in courts; Supreme Court ruling created controversy over due process rights for deportees sent to El Salvador's CECOT mega-prison.",
      status: "enacted", category: "immigration", proposedDate: "2025-03-15",
      proposedBy: "Trump Administration",
      supportingParties: ["Republican Party"],
      opposingParties: ["Democratic Party", "ACLU", "Federal Courts"],
      publicOpinion: "mixed",
      impact: "Hundreds of Venezuelans deported to El Salvador's CECOT prison; legal challenges ongoing in Supreme Court",
      controversyLevel: "high",
    },
    {
      country: "United Kingdom", countryCode: "GB",
      title: "Digital Markets, Competition and Consumers Act",
      description: "Legislation designating tech giants (Google, Apple, Meta, Amazon, Microsoft) as 'Strategic Market Status' firms subject to mandatory conduct requirements set by CMA. Fines up to 10% of global turnover for breaches.",
      status: "enacted", category: "technology", proposedDate: "2024-01-01",
      enactedDate: "2024-05-24",
      proposedBy: "Labour Government",
      supportingParties: ["Labour", "Liberal Democrats"],
      opposingParties: ["Conservative Party (partially)"],
      publicOpinion: "favorable",
      impact: "Major tech platforms must open interoperability and app store competition. Big Tech lobbying intensely against enforcement.",
      controversyLevel: "moderate",
    },
    {
      country: "India", countryCode: "IN",
      title: "Digital Personal Data Protection Act (DPDPA) — Implementation Rules",
      description: "Implementation rules for India's landmark data protection law requiring consent for data processing, data localization options, and creating Data Protection Board. Critics argue government exemptions are too broad and undermine the protection.",
      status: "debate", category: "technology", proposedDate: "2025-06-01",
      proposedBy: "Ministry of Electronics and IT",
      supportingParties: ["BJP"],
      opposingParties: ["Opposition (exemptions too broad)", "Tech industry (compliance burden)"],
      publicOpinion: "mixed",
      impact: "Affects all companies processing Indian citizen data including WhatsApp (500M users), Google, Amazon",
      controversyLevel: "moderate",
    },
    {
      country: "European Union", countryCode: "EU",
      title: "EU AI Act — High Risk Applications Implementation",
      description: "Phase 2 implementation of world's first comprehensive AI regulation law. High-risk AI systems in healthcare, education, employment, and critical infrastructure must now comply with transparency, accuracy, and human oversight requirements. Prohibited AI systems (social scoring, emotion recognition in workplaces) enforcement begins.",
      status: "enacted", category: "technology", proposedDate: "2023-06-14",
      enactedDate: "2026-08-02",
      proposedBy: "European Commission",
      supportingParties: ["EPP", "S&D", "Renew Europe"],
      opposingParties: ["France (initially, to protect national AI)"],
      publicOpinion: "favorable",
      impact: "Global compliance standard for all AI companies selling into EU market. Fines up to €35M or 7% global revenue.",
      controversyLevel: "moderate",
    },
    {
      country: "China", countryCode: "CN",
      title: "Private Economy Promotion Law",
      description: "First-ever law specifically protecting private enterprise in China, guaranteeing equal market access, property rights protection, and limits on arbitrary government seizures. Seen as response to private sector collapse in confidence following tech crackdowns on Alibaba, Didi, Meituan (2020-2022).",
      status: "enacted", category: "economy", proposedDate: "2024-09-01",
      enactedDate: "2025-10-01",
      proposedBy: "State Council",
      supportingParties: ["Chinese Communist Party"],
      opposingParties: [],
      publicOpinion: "favorable",
      impact: "Private sector investment recovery; Jack Ma returned to China; Alibaba market cap recovered 40%",
      controversyLevel: "low",
    },
    {
      country: "Russia", countryCode: "RU",
      title: "Mobilization Reserve Law — Second Wave Conscription",
      description: "Classified legislation reportedly authorizing a second mobilization of up to 500,000 additional troops for the Ukraine war. Details not publicly disclosed but leaked to opposition media. Intensely unpopular; triggered border crossing surges when first mobilization was announced.",
      status: "proposed", category: "military", proposedDate: "2026-02-01",
      proposedBy: "Kremlin / Ministry of Defense",
      supportingParties: ["United Russia"],
      opposingParties: ["Russian civil society (suppressed)"],
      publicOpinion: "opposed",
      impact: "Potential 500,000 additional troops drafted; significant emigration pressure on military-age Russian men",
      controversyLevel: "high",
    },
    {
      country: "Israel", countryCode: "IL",
      title: "Ultra-Orthodox Military Draft Law",
      description: "Supreme Court-mandated legislation requiring Haredi (ultra-Orthodox) men to serve in IDF alongside secular Israelis, ending 75-year exemption. Threatens to collapse Netanyahu's coalition which depends on ultra-Orthodox parties. Major flashpoint in Israeli society during Gaza war.",
      status: "debate", category: "military", proposedDate: "2025-03-01",
      proposedBy: "Supreme Court Order (Netanyahu forced to legislate)",
      supportingParties: ["Opposition parties", "IDF leadership"],
      opposingParties: ["Shas", "United Torah Judaism (coalition partners)"],
      publicOpinion: "favorable",
      impact: "Could collapse Netanyahu coalition; 60,000 Haredi men immediately eligible for IDF service",
      controversyLevel: "high",
    },
  ]).returning();

  console.log(`Seeded ${legislation.length} legislation`);

  // ── CRIMINAL CASES ───────────────────────────────────────────────────────
  await db.delete(criminalCasesTable);
  const criminalCases = await db.insert(criminalCasesTable).values([
    {
      title: "Netanyahu Corruption Trial (Cases 1000, 2000, 4000)",
      country: "Israel",
      court: "Jerusalem District Court",
      caseType: "corruption",
      status: "trial",
      defendants: ["Benjamin Netanyahu"],
      charges: ["Bribery (Case 4000 — Bezeq telecom)", "Fraud and breach of trust (Cases 1000, 2000)"],
      description: "Israel's longest-running political trial. Netanyahu charged in three separate cases: accepting gifts from wealthy businessmen (cigars, champagne, jewelry worth ~$200,000); negotiating favorable press coverage with Yedioth Ahronoth publisher; and granting regulatory benefits worth $500M+ to Bezeq telecoms in exchange for favorable coverage on Walla news site.",
      startDate: "2020-05-24",
      internationalInvolvement: false,
      severity: "serious",
    },
    {
      title: "ICC Case Against Vladimir Putin — Deportation of Ukrainian Children",
      country: "Russia",
      court: "International Criminal Court (The Hague)",
      caseType: "war crimes",
      status: "investigation",
      defendants: ["Vladimir Putin", "Maria Lvova-Belova (Children's Rights Commissioner)"],
      charges: ["War crime of unlawful deportation of population", "War crime of unlawful transfer of population (children from occupied Ukraine to Russia)"],
      description: "ICC Pre-Trial Chamber II issued arrest warrants for Putin and Lvova-Belova on March 17, 2023. Approximately 16,000+ Ukrainian children documented as deported to Russia for 're-education' and adoption into Russian families. Putin cannot travel to the 124 ICC member states without risk of arrest. Marks first ICC warrant for a sitting G8-level leader.",
      startDate: "2023-03-17",
      internationalInvolvement: true,
      severity: "severe",
    },
    {
      title: "ICC Case Against Netanyahu and Gallant — Gaza War Crimes",
      country: "Israel",
      court: "International Criminal Court (The Hague)",
      caseType: "war crimes",
      status: "investigation",
      defendants: ["Benjamin Netanyahu", "Yoav Gallant (former Defense Minister)"],
      charges: ["Crime against humanity: starvation as a method of warfare", "Crime against humanity: murder, persecution", "War crime: directing attacks against civilians", "War crime: using starvation as method of warfare"],
      description: "ICC arrest warrants issued November 21, 2024. First ICC warrants against sitting leaders of a Western-aligned democracy. Prosecutor Karim Khan cited systematic denial of humanitarian aid to Gaza civilians as primary evidence. US, UK, Germany initially disputed ICC jurisdiction but several European states indicated they would enforce the warrant. Netanyahu confirmed he cannot travel to 124 ICC member states.",
      startDate: "2024-11-21",
      internationalInvolvement: true,
      severity: "severe",
    },
    {
      title: "Imran Khan — Cipher Case and Corruption Charges",
      country: "Pakistan",
      court: "Special Court Islamabad / Accountability Court",
      caseType: "corruption",
      status: "trial",
      defendants: ["Imran Khan"],
      charges: ["Official Secrets Act violation (Cipher case)", "Corrupt practices — state gifts (Toshakhana)", "Terrorism charges (multiple FIRs)", "Anti-terrorism act violations"],
      description: "Former Pakistan PM Imran Khan arrested May 2023, in custody since August 2023. Faces 150+ cases including: leaking sensitive cipher (diplomatic cable) from Washington DC; illegally selling state gifts; and terrorism charges stemming from May 9, 2023 riots when supporters attacked army installations. Widely seen as politically motivated prosecution by military establishment that engineered his removal from power in 2022.",
      startDate: "2023-05-09",
      internationalInvolvement: false,
      severity: "serious",
    },
    {
      title: "Sam Bankman-Fried (SBF) — FTX Fraud and Conspiracy",
      country: "United States",
      court: "Southern District of New York (SDNY)",
      caseType: "fraud",
      status: "convicted",
      defendants: ["Samuel Bankman-Fried"],
      charges: ["Wire fraud", "Conspiracy to commit wire fraud", "Securities fraud", "Commodities fraud", "Money laundering"],
      description: "Founder of FTX cryptocurrency exchange found guilty on all 7 counts in November 2023. FTX collapsed in November 2022 wiping out $8 billion in customer funds. SBF sentenced to 25 years in federal prison in March 2024 in one of the largest financial frauds in US history. Co-conspirators Caroline Ellison, Gary Wang, and Nishad Singh cooperated with prosecutors.",
      startDate: "2022-11-11",
      verdict: "Guilty on all 7 counts",
      sentencing: "25 years federal prison",
      internationalInvolvement: true,
      severity: "serious",
    },
    {
      title: "Myanmar Junta Leaders — ICJ Genocide Case (Rohingya)",
      country: "Myanmar",
      court: "International Court of Justice / International Criminal Court",
      caseType: "genocide",
      status: "trial",
      defendants: ["Min Aung Hlaing (Commander-in-Chief, Myanmar Armed Forces)", "Senior Junta Officials"],
      charges: ["Genocide against Rohingya Muslim minority", "Crimes against humanity", "War crimes — systematic rape, murder, destruction of villages"],
      description: "ICJ case brought by Gambia on behalf of OIC 2019. Myanmar military (Tatmadaw) conducted 'clearance operations' in 2016-2017 killing 10,000+ Rohingya, gang-raping women, burning 350+ villages, driving 700,000+ to Bangladesh. UN fact-finding mission concluded genocide was committed. Min Aung Hlaing also led 2021 coup deposing Aung San Suu Kyi. ICC issued arrest warrant in 2023.",
      startDate: "2019-11-11",
      internationalInvolvement: true,
      severity: "severe",
    },
    {
      title: "French Far-Right — Marine Le Pen EU Funds Embezzlement",
      country: "France",
      court: "Paris Correctional Court",
      caseType: "corruption",
      status: "convicted",
      defendants: ["Marine Le Pen", "RN Party Officials"],
      charges: ["Embezzlement of EU Parliamentary funds", "Misuse of European Parliament resources"],
      description: "Marine Le Pen and her National Rally (RN) party convicted in March 2025 of misusing €4.5 million in EU Parliamentary funds for party work in France rather than EU parliamentary work as required. Le Pen sentenced to 4 years prison (2 suspended, 2 with ankle monitor) and ineligibility from public office for 5 years. Sentence under appeal — if upheld, bars her from 2027 presidential election.",
      startDate: "2016-06-01",
      verdict: "Guilty — Le Pen and 25 others",
      sentencing: "4 years (2 suspended + 2 ankle monitor); 5-year ineligibility from office",
      internationalInvolvement: false,
      severity: "serious",
    },
    {
      title: "Saudi Arabia — Jamal Khashoggi Murder Case",
      country: "Saudi Arabia",
      court: "Turkish Courts / UN Special Rapporteur Investigation",
      caseType: "human rights",
      status: "convicted",
      defendants: ["Saudi Hit Team (7 members)", "Saud al-Qahtani (MBS adviser, indicted)"],
      charges: ["Premeditated murder", "Conspiracy to commit murder", "Dismemberment of body"],
      description: "Washington Post journalist Jamal Khashoggi murdered and dismembered at Saudi consulate in Istanbul on October 2, 2018. Turkish authorities covertly recorded the murder. Saudi Arabia initially denied, then claimed rogue operation. CIA concluded Crown Prince MBS directly ordered the killing. Five operatives sentenced to 20 years in Saudi court; two others received lesser sentences. MBS not charged — Western governments imposed limited sanctions.",
      startDate: "2018-10-02",
      verdict: "Saudi courts convicted 8 operatives; MBS not charged",
      sentencing: "5 operatives: 20 years; 3 others: lesser sentences",
      internationalInvolvement: true,
      severity: "severe",
    },
  ]).returning();

  console.log(`Seeded ${criminalCases.length} criminal cases`);

  // ── INTERPOL NOTICES ─────────────────────────────────────────────────────
  await db.delete(interpolTable);
  const interpol = await db.insert(interpolTable).values([
    {
      noticeType: "red", subjectName: "Yahya Sinwar (Deceased — Notice Cancelled)",
      nationality: "Palestinian", chargedBy: "United States, Israel",
      charges: "Terrorism, Conspiracy to commit murder, Taking of hostages, Crimes against humanity",
      description: "Former Hamas Political Bureau Chief and architect of the October 7, 2023 terrorist attacks against Israel. Personally oversaw planning of attacks killing 1,200+ and taking 251 hostages. Killed in IDF ground operation in Rafah, October 16, 2024. Notice retroactively documented.",
      dangerLevel: "extreme", lastKnownLocation: "Deceased — Rafah, Gaza",
      status: "cancelled", issuedDate: "2023-10-07",
    },
    {
      noticeType: "red", subjectName: "Mohammed Deif (Deceased — Notice Cancelled)",
      nationality: "Palestinian", chargedBy: "United States, Israel, European Union",
      charges: "Terrorism, Planning and execution of mass murder, Arms trafficking",
      description: "Hamas military commander and mastermind behind October 7 attacks. Led Hamas military wing Izz ad-Din al-Qassam Brigades for 25+ years. Survived 7 previous assassination attempts (lost eye, arm, leg). Killed in IDF airstrike July 13, 2024 (confirmed by Israel October 2024). Most wanted terrorist for three decades.",
      dangerLevel: "extreme", lastKnownLocation: "Deceased — Khan Younis, Gaza",
      status: "cancelled", issuedDate: "2023-10-15",
    },
    {
      noticeType: "red", subjectName: "Dawood Ibrahim Kaskar",
      nationality: "Indian", chargedBy: "India, United States",
      charges: "Terrorism, 1993 Bombay bombings (257 dead), Drug trafficking, Organized crime",
      description: "Head of D-Company criminal empire. Orchestrated 1993 Bombay serial bombings killing 257 people. Designated global terrorist by UN and US (2003). Believed sheltered by Pakistani ISI in Karachi, Pakistan. Controls extensive criminal network spanning South Asia, Middle East, and Europe. Interpol red notice since 1993. Reward: $25 million (US).",
      dangerLevel: "extreme", lastKnownLocation: "Karachi, Pakistan (alleged)",
      status: "active", issuedDate: "1993-03-13",
    },
    {
      noticeType: "red", subjectName: "Ayman al-Zawahiri (Deceased — Notice Cancelled)",
      nationality: "Egyptian", chargedBy: "United States",
      charges: "Terrorism, 9/11 attacks planning, US embassy bombings, Conspiracy to murder",
      description: "Al-Qaeda leader following bin Laden's death. Egyptian physician turned terrorist. Co-planned 9/11 attacks (2001), 1998 US embassy bombings in Kenya and Tanzania. Killed by CIA drone strike in Kabul, Afghanistan, July 31, 2022 while under Taliban protection on apartment balcony.",
      dangerLevel: "extreme", lastKnownLocation: "Deceased — Kabul, Afghanistan",
      status: "cancelled", issuedDate: "2001-09-12",
    },
    {
      noticeType: "red", subjectName: "Nicolás Maduro Moros",
      nationality: "Venezuelan", chargedBy: "United States",
      charges: "Narco-terrorism, Drug trafficking conspiracy, Conspiracy with FARC",
      description: "President of Venezuela. US Department of Justice indicted Maduro in March 2020 on narco-terrorism charges alleging he worked with Colombian FARC rebels to 'flood the United States with cocaine.' $15 million US reward. Maduro controls Venezuela as authoritarian leader since 2013. US does not recognize his 2024 re-election as legitimate.",
      dangerLevel: "high", lastKnownLocation: "Caracas, Venezuela",
      status: "active", issuedDate: "2020-03-26",
    },
    {
      noticeType: "red", subjectName: "Hassan Nasrallah (Deceased — Notice Cancelled)",
      nationality: "Lebanese", chargedBy: "United States, Israel, Gulf Cooperation Council",
      charges: "Terrorism, Planning attacks against civilians, Arms proliferation",
      description: "Secretary-General of Hezbollah, the Lebanese Shia militant group and political party. Led Hezbollah since 1992. Built Hezbollah into one of world's most powerful non-state military forces with 150,000+ rockets and drones. Killed in Israeli airstrike on Hezbollah HQ in Beirut, September 27, 2024.",
      dangerLevel: "extreme", lastKnownLocation: "Deceased — Beirut, Lebanon",
      status: "cancelled", issuedDate: "2006-07-01",
    },
    {
      noticeType: "orange", subjectName: "Wagner Group / Africa Corps (Russia)",
      nationality: "Russian", chargedBy: "EU, US, UK, France",
      charges: "War crimes in Ukraine, Mali, CAR, Libya, Sudan; Civilian massacres; Mercenary activity",
      description: "Russian private military company now rebranded as 'Africa Corps' post-Prigozhin death. Active in 15+ countries. Documented war crimes in Ukraine (Bucha, Mariupol), Mali (Moura massacre 500+ civilians), CAR (systematic rape, killing). Designated terrorist organization by EU and US. Leadership now under Russian MoD control after Prigozhin death.",
      dangerLevel: "extreme", lastKnownLocation: "Active in Mali, Niger, Libya, Sudan, Ukraine, Syria",
      status: "active", issuedDate: "2023-06-01",
    },
    {
      noticeType: "red", subjectName: "Semyon Mogilevich",
      nationality: "Russian/Ukrainian", chargedBy: "United States (FBI)",
      charges: "Racketeering, Securities fraud, Wire fraud, Mail fraud, Money laundering",
      description: "On FBI's Ten Most Wanted list. Ukrainian-born organized crime boss known as 'The Brainy Don.' Controls RosUkrEnergo gas trading scheme, YBM Magnex securities fraud ($150M), arms trafficking, drug trafficking, prostitution. Based in Moscow under FSB protection. Considered world's most dangerous mob boss by FBI.",
      dangerLevel: "extreme", lastKnownLocation: "Moscow, Russia (protected by FSB)",
      status: "active", issuedDate: "1999-10-14",
    },
  ]).returning();

  console.log(`Seeded ${interpol.length} interpol notices`);

  // ── ICJ CASES ────────────────────────────────────────────────────────────
  await db.delete(icjTable);
  const icj = await db.insert(icjTable).values([
    {
      title: "Ukraine v. Russia — Allegations of Genocide under Genocide Convention",
      applicantCountry: "Ukraine",
      respondentCountry: "Russia",
      caseType: "genocide / treaty interpretation",
      status: "hearings",
      filedDate: "2022-02-27",
      description: "Filed 3 days after Russia's full-scale invasion. Ukraine argues Russia's claims of 'genocide' in Donbas used as false pretext for invasion violate the Genocide Convention. Court issued provisional measures ordering Russia to immediately suspend military operations (which Russia ignored). Merits hearings ongoing.",
      currentPhase: "Merits — oral hearings scheduled 2026",
      lastUpdate: "Court upheld jurisdiction despite Russian objections; merits phase continuing",
      significance: "landmark",
    },
    {
      title: "South Africa v. Israel — Application of Genocide Convention (Gaza)",
      applicantCountry: "South Africa",
      respondentCountry: "Israel",
      caseType: "genocide",
      status: "hearings",
      filedDate: "2023-12-29",
      description: "South Africa alleges Israel is committing genocide against Palestinians in Gaza in violation of the 1948 Genocide Convention. Court issued landmark provisional measures in January 2024 ordering Israel to take all measures to prevent genocidal acts, though did not order immediate ceasefire. As of 2026, proceedings continuing with 50+ countries filing declarations of intervention.",
      currentPhase: "Preliminary hearings; provisional measures implemented; merits phase filing",
      lastUpdate: "50+ countries intervened; Nicaragua, Colombia joined; full merits phase scheduled 2027",
      significance: "landmark",
    },
    {
      title: "Nicaragua v. Germany — Genocide Convention (Gaza Arms Supply)",
      applicantCountry: "Nicaragua",
      respondentCountry: "Germany",
      caseType: "genocide complicity",
      status: "preliminary",
      filedDate: "2024-03-01",
      description: "Nicaragua alleges Germany is complicit in genocide in Gaza by supplying arms to Israel. Germany suspended most arms exports to Israel in January 2024 pending review. Court ruled it has prima facie jurisdiction but rejected provisional measures in April 2024. First case testing whether arms suppliers can be held liable.",
      currentPhase: "Preliminary objections phase",
      lastUpdate: "Provisional measures rejected April 2024; preliminary objections filed",
      significance: "high",
    },
    {
      title: "Somalia v. Kenya — Maritime Boundary Dispute (Indian Ocean)",
      applicantCountry: "Somalia",
      respondentCountry: "Kenya",
      caseType: "maritime boundary",
      status: "judgment",
      filedDate: "2014-08-28",
      description: "Dispute over 100,000 sq km of Indian Ocean maritime boundary rich in oil and gas deposits. Kenya disputed court's jurisdiction; overruled. Court delivered judgment October 2021 largely accepting Somalia's equidistance boundary. Kenya initially refused to accept judgment. Significant for offshore hydrocarbon rights.",
      currentPhase: "Post-judgment — Kenya implementing delimitation",
      lastUpdate: "Kenya accepted judgment in 2023; boundary demarcation ongoing",
      significance: "high",
    },
    {
      title: "Qatar v. UAE — Racial Discrimination Convention",
      applicantCountry: "Qatar",
      respondentCountry: "United Arab Emirates",
      caseType: "racial discrimination / treaty",
      status: "concluded",
      filedDate: "2018-06-11",
      description: "Qatar alleged UAE discriminated against Qatari nationals by expelling them and cutting ties during the 2017 Gulf blockade. UAE argued court lacked jurisdiction. Court ruled it had jurisdiction (2021); case terminated in 2023 following the Al-Ula Agreement reconciliation between Qatar and Gulf states.",
      currentPhase: "Concluded — case removed from general list following reconciliation",
      lastUpdate: "Case terminated 2023 following Qatar-UAE normalization",
      significance: "moderate",
    },
    {
      title: "Armenia v. Azerbaijan — Convention on Elimination of Racial Discrimination",
      applicantCountry: "Armenia",
      respondentCountry: "Azerbaijan",
      caseType: "racial discrimination / humanitarian",
      status: "hearings",
      filedDate: "2021-09-16",
      description: "Armenia alleges Azerbaijan systematically discriminated against and expelled ethnic Armenians from Nagorno-Karabakh. After Azerbaijan's September 2023 offensive, the entire Armenian population of Karabakh (120,000 people) fled to Armenia in what has been called ethnic cleansing. Court issued multiple provisional measures orders.",
      currentPhase: "Merits proceedings — evidence submission phase",
      lastUpdate: "Court ordered Azerbaijan to ensure free movement to Karabakh (largely ignored); ethnic cleansing completed",
      significance: "high",
    },
    {
      title: "Gambia v. Myanmar — Rohingya Genocide Case",
      applicantCountry: "Gambia",
      respondentCountry: "Myanmar",
      caseType: "genocide",
      status: "hearings",
      filedDate: "2019-11-11",
      description: "Gambia filed on behalf of OIC (57 Muslim-majority states). Myanmar military's 2016-2017 'clearance operations' killed 10,000+ Rohingya Muslims, sexually assaulted women, burned 350+ villages, forcibly displaced 700,000+. Court issued provisional measures requiring Myanmar to protect Rohingya. Myanmar junta refuses to engage with proceedings since 2021 coup.",
      currentPhase: "Preliminary objections overruled; merits phase",
      lastUpdate: "Myanmar junta refused to participate since 2021 coup; court continuing in absence",
      significance: "landmark",
    },
  ]).returning();

  console.log(`Seeded ${icj.length} ICJ cases`);

  // ── TREATIES ─────────────────────────────────────────────────────────────
  await db.delete(treatiesTable);
  const treaties = await db.insert(treatiesTable).values([
    {
      title: "Russia-North Korea Comprehensive Strategic Partnership Treaty",
      type: "defense / strategic",
      signatories: ["Russia", "North Korea"],
      status: "in force",
      signedDate: "2024-06-19",
      effectiveDate: "2024-11-04",
      description: "Signed by Putin and Kim Jong-un in Pyongyang. Article 4 commits each party to provide military and other assistance if either faces armed aggression — mirroring NATO Article 5 mutual defense. Enables North Korea to supply Russia with artillery shells, missiles, and troops for Ukraine war in exchange for Russian technology transfers (satellite, nuclear submarine). Ratified by Russian Duma November 2024.",
      significance: "landmark",
      relatedConflicts: [],
    },
    {
      title: "Abraham Accords (UAE, Bahrain, Sudan, Morocco normalization with Israel)",
      type: "peace / normalization",
      signatories: ["Israel", "United Arab Emirates", "Bahrain", "Sudan", "Morocco"],
      status: "in force",
      signedDate: "2020-09-15",
      effectiveDate: "2020-09-15",
      description: "US-brokered normalization agreements between Israel and four Arab states during Trump's first term. UAE and Bahrain signed at White House in September 2020; Sudan and Morocco followed. First Arab-Israeli peace deals since Jordan (1994). Saudi Arabia normalization was under active negotiation before October 7, 2023 attacks derailed progress. Reshaped Middle East geopolitics.",
      significance: "landmark",
      relatedConflicts: [],
    },
    {
      title: "Treaty on the Prohibition of Nuclear Weapons (TPNW)",
      type: "nuclear disarmament",
      signatories: ["93 signatory states (not US, Russia, China, UK, France, India, Pakistan, Israel, North Korea)"],
      status: "in force",
      signedDate: "2017-07-07",
      effectiveDate: "2021-01-22",
      description: "UN treaty comprehensively banning nuclear weapons. First legally binding international agreement to prohibit nuclear weapons including development, production, stockpiling, and use. All 9 nuclear-armed states boycotted negotiations and refuse to sign. All NATO states (except Netherlands — observer) also refuse to join. Symbolic importance; limited practical effect without major nuclear powers.",
      significance: "high",
      relatedConflicts: [],
    },
    {
      title: "Paris Agreement on Climate Change",
      type: "environmental",
      signatories: ["196 Parties (UNFCCC)"],
      status: "in force",
      signedDate: "2016-04-22",
      effectiveDate: "2016-11-04",
      description: "Landmark global climate treaty. Countries commit to limiting global warming to well below 2°C, pursuing 1.5°C, through nationally determined contributions (NDCs). US withdrew under Trump (2020), rejoined under Biden (2021), withdrew again under Trump (2025). China, world's largest emitter, committed to carbon neutrality by 2060. Implementation critically behind targets.",
      significance: "landmark",
      relatedConflicts: [],
    },
    {
      title: "NATO Strategic Concept 2022 — Russia 'Gravest Threat' Declaration",
      type: "collective defense / strategic",
      signatories: ["32 NATO Member States"],
      status: "in force",
      signedDate: "2022-06-29",
      effectiveDate: "2022-06-29",
      description: "NATO's foundational strategic document for the decade, agreed at Madrid Summit. Formally declares Russia 'the most significant and direct threat to the security of Allies.' First time China mentioned as security challenge. Finland and Sweden accelerated accession. Commits to 300,000+ high-readiness forces. 2% GDP defence spending minimum mandatory.",
      significance: "landmark",
      relatedConflicts: [],
    },
    {
      title: "Iran Nuclear Deal — JCPOA (Joint Comprehensive Plan of Action)",
      type: "nuclear non-proliferation",
      signatories: ["Iran", "United States", "Russia", "China", "France", "Germany", "United Kingdom"],
      status: "violated",
      signedDate: "2015-07-14",
      effectiveDate: "2016-01-16",
      description: "Landmark agreement limiting Iran's nuclear program in exchange for sanctions relief. US withdrew under Trump in 2018 ('maximum pressure' campaign). Iran began violating enrichment limits in 2019, reaching 84% enrichment (weapon-grade is 90%). Biden restoration talks failed in 2022. As of 2026, Iran has enriched sufficient uranium for multiple nuclear weapons; JCPOA effectively dead.",
      significance: "landmark",
      relatedConflicts: [],
    },
    {
      title: "Ukraine EU Association Agreement",
      type: "trade / political",
      signatories: ["Ukraine", "European Union"],
      status: "in force",
      signedDate: "2014-06-27",
      effectiveDate: "2017-09-01",
      description: "Deep and Comprehensive Free Trade Agreement that triggered the 2014 Euromaidan revolution when Yanukovych refused to sign under Russian pressure. Creates deep trade integration and political association with EU. Ukraine's refusal to abandon this agreement was a stated factor in Russia's 2022 invasion. Ukraine granted EU candidate status June 2022; accession negotiations ongoing.",
      significance: "landmark",
      relatedConflicts: [],
    },
    {
      title: "US-Saudi Arabia Mutual Defense Agreement (Proposed — 2024)",
      type: "defense / bilateral",
      signatories: ["United States", "Saudi Arabia (pending)"],
      status: "draft",
      signedDate: "2024-05-01",
      effectiveDate: null,
      description: "Biden administration proposed unprecedented mutual defense treaty with Saudi Arabia as part of broader normalization framework that included Saudi-Israel normalization. Saudi Arabia demanded US security guarantees, assistance with civilian nuclear program, and advanced weapons before normalizing with Israel. October 7 attacks disrupted timeline. Trump administration revived discussions in 2025 with modified terms.",
      significance: "high",
      relatedConflicts: [],
    },
  ]).returning();

  console.log(`Seeded ${treaties.length} treaties`);

  // ── MEDIA EVENTS ─────────────────────────────────────────────────────────
  await db.delete(mediaEventsTable);
  const mediaEvents = await db.insert(mediaEventsTable).values([
    {
      title: "Operation Sindoor — India Strikes Pakistan Terror Camps",
      country: "India", countryCode: "IN",
      category: "military strike", severity: "historic",
      description: "India launched precision missile and air strikes on 9 terror infrastructure targets across Pakistan and Pakistan-occupied Kashmir on May 7, 2025, following the Pahalgam massacre of 26 Hindu tourists by Pakistan-based Lashkar-e-Taiba militants. Named 'Operation Sindoor' — sindoor (vermilion) worn by married Hindu women as tribute to widows of victims. Largest India-Pakistan military exchange since 1971. Both nuclear powers mobilized forces; US and China brokered ceasefire after 4 days.",
      date: "2025-05-07", source: "Multiple verified sources",
      isVerified: true, tags: ["India-Pakistan", "Military", "Terrorism", "Nuclear Risk"],
    },
    {
      title: "Hamas October 7 Attacks — Israel's Deadliest Day",
      country: "Israel", countryCode: "IL",
      category: "terrorist attack", severity: "historic",
      description: "Hamas and Islamic Jihad breached Israel's Gaza border fence at 6:29 AM on October 7, 2023 (Shabbat + Simchat Torah holiday). 3,000+ terrorists attacked 22 Israeli communities. 1,200 Israelis killed (Holocaust survivor grandparents to infants), 251 taken hostage to Gaza. Kibbutz Kfar Aza, Be'eri, and Nir Oz massacred. Nova music festival attacked — 364 festival-goers murdered. Deadliest single-day killing of Jews since the Holocaust.",
      date: "2023-10-07", source: "IDF, Israeli government, international press",
      isVerified: true, tags: ["Hamas", "Terrorism", "Israel", "Gaza", "Hostages"],
    },
    {
      title: "Wagner Group Mutiny — Prigozhin's March on Moscow",
      country: "Russia", countryCode: "RU",
      category: "political crisis", severity: "historic",
      description: "June 23-24, 2023: Wagner PMC chief Yevgeny Prigozhin launched armed mutiny against Russian military leadership, seizing Rostov-on-Don military HQ and marching armored column 500 miles toward Moscow before stopping following Belarus-brokered deal. Exposed cracks in Putin's hold on power. Prigozhin died in plane crash August 23, 2023, widely attributed to Putin assassination order. Most dramatic challenge to Kremlin power since 1991.",
      date: "2023-06-23", source: "Reuters, BBC, Kremlin sources",
      isVerified: true, tags: ["Russia", "Wagner", "Prigozhin", "Mutiny", "Putin"],
    },
    {
      title: "Turkey-Syria Earthquake — 60,000+ Killed",
      country: "Turkey", countryCode: "TR",
      category: "natural disaster", severity: "historic",
      description: "Two catastrophic earthquakes struck southern Turkey and northwestern Syria on February 6, 2023. Magnitude 7.8 followed by 7.7 just 9 hours later. 11 Turkish provinces affected; 60,000+ confirmed dead (Turkey 50,000+, Syria 10,000+). 1.5 million displaced. 300,000+ buildings destroyed. Erdogan government's slow response and construction industry corruption ('earthquake buildings') major political scandal.",
      date: "2023-02-06", source: "AFAD (Turkey), UN, WHO",
      isVerified: true, tags: ["Turkey", "Syria", "Earthquake", "Disaster", "Reconstruction"],
    },
    {
      title: "Chinese Spy Balloon Incident — US Shoots Down Surveillance Balloon",
      country: "China", countryCode: "CN",
      category: "diplomatic incident", severity: "major",
      description: "Chinese high-altitude balloon crossed continental United States February 2023, flying over Montana ICBM silos and other sensitive military installations. Biden administration waited until balloon was over Atlantic Ocean before shooting it down with F-22 fighter jet on February 4, 2023. China claimed weather balloon; US Pentagon said it carried surveillance equipment. Triggered diplomatic crisis, Blinken cancelled Beijing trip. Later reports found balloons had traversed 40+ countries.",
      date: "2023-02-04", source: "Pentagon, State Department, US media",
      isVerified: true, tags: ["China", "Espionage", "US-China", "Military"],
    },
    {
      title: "BRICS Expansion — Saudi Arabia, UAE, Iran, Ethiopia, Egypt Join",
      country: "South Africa", countryCode: "ZA",
      category: "geopolitical", severity: "major",
      description: "At Johannesburg summit in August 2023, BRICS invited Saudi Arabia, UAE, Iran, Ethiopia, Egypt, and Argentina to join (Argentina declined under Milei). BRICS+ bloc now represents 45% of world population and 36% of global GDP (PPP). Seen as pivot toward non-Western multipolar order. Saudi Arabia-Iran rapprochement (China-brokered 2023) enabled both joining simultaneously. Major shift in global power architecture.",
      date: "2023-08-24", source: "BRICS Summit Johannesburg Declaration",
      isVerified: true, tags: ["BRICS", "Multipolarity", "Global Order", "Saudi Arabia", "Iran"],
    },
    {
      title: "UK Government Collapse — Liz Truss Resigns After 45 Days",
      country: "United Kingdom", countryCode: "GB",
      category: "political crisis", severity: "major",
      description: "Liz Truss's 'mini-budget' (September 23, 2022) with £45B unfunded tax cuts triggered bond market meltdown, pound fell to near-parity with dollar, Bank of England emergency intervention. She reversed all policies within weeks. Resigned October 20, 2022 — shortest-serving UK Prime Minister in history at 45 days. 'Lettuce' coverage went viral (Daily Star put lettuce webcam). Rishi Sunak became PM without election.",
      date: "2022-10-20", source: "Hansard, UK media",
      isVerified: true, tags: ["UK", "Political Crisis", "Economy", "Conservative Party"],
    },
    {
      title: "Nord Stream Pipeline Sabotage — Mystery Underwater Explosions",
      country: "Russia", countryCode: "RU",
      category: "sabotage", severity: "major",
      description: "Explosions destroyed three of four Nord Stream 1 and 2 pipeline sections on September 26, 2022 under the Baltic Sea. Pipelines carried Russian gas to Europe. Multiple investigations launched by Sweden, Denmark, Germany. Sweden closed investigation without assigning blame (2024). Seymour Hersh report (2023) blamed US Navy divers; US denied. German investigation traced to pro-Ukraine yacht ('Andromeda'), possibly connected to Ukrainian operators. Largest infrastructure sabotage in European peacetime history.",
      date: "2022-09-26", source: "Multiple governments, Seymour Hersh, NYT",
      isVerified: true, tags: ["Russia", "Germany", "Europe", "Energy", "Sabotage", "Ukraine War"],
    },
    {
      title: "Narendra Modi Wins Third Term — Coalition Government",
      country: "India", countryCode: "IN",
      category: "election", severity: "major",
      description: "India's 2024 general election (world's largest democratic exercise — 970 million voters). BJP lost outright majority for first time since 2014, winning 240 seats (down from 303). Modi continues as PM in NDA coalition with allies (272 minimum required). Opposition INDIA alliance won 234 seats — more than expected. Result seen as partial rebuke of BJP's Hindu nationalist agenda. Modi's weakened position has constrained some policy initiatives.",
      date: "2024-06-04", source: "Election Commission of India",
      isVerified: true, tags: ["India", "Election", "Modi", "BJP", "Democracy"],
    },
    {
      title: "Netanyahu ICC Arrest Warrant — First Western-Allied Leader Targeted",
      country: "Israel", countryCode: "IL",
      category: "legal", severity: "historic",
      description: "International Criminal Court Pre-Trial Chamber I issued arrest warrants for Israeli PM Benjamin Netanyahu and former Defense Minister Yoav Gallant on November 21, 2024. Charges include using starvation as weapon of war and directing attacks against civilians in Gaza. First ICC arrest warrants against leaders of a Western-aligned democracy. US (non-member) rejected warrant; European states divided on enforcement obligations.",
      date: "2024-11-21", source: "ICC Press Release, multiple governments",
      isVerified: true, tags: ["Israel", "ICC", "War Crimes", "Gaza", "Netanyahu", "International Law"],
    },
    {
      title: "Silicon Valley Bank Collapse — Second Largest US Bank Failure in History",
      country: "United States", countryCode: "US",
      category: "economic crisis", severity: "major",
      description: "Silicon Valley Bank (SVB) failed March 10, 2023 after bank run triggered by rising interest rates destroying bond portfolio value. $175 billion in deposits at risk. FDIC seized bank; US government guaranteed all deposits (beyond $250K FDIC limit) to prevent contagion. Signature Bank failed same weekend. Credit Suisse required emergency Swiss government-brokered UBS takeover. Triggered global banking sector anxiety. Exposed tech startup ecosystem fragility.",
      date: "2023-03-10", source: "FDIC, Federal Reserve, WSJ",
      isVerified: true, tags: ["US", "Banking", "Financial Crisis", "SVB", "Tech"],
    },
    {
      title: "France — Race Riots After Police Kill Nahel Merzouk",
      country: "France", countryCode: "FR",
      category: "social unrest", severity: "major",
      description: "17-year-old Nahel Merzouk shot dead by police officer during traffic stop in Nanterre, June 27, 2023. Video of shooting went viral. France erupted in its worst riots since 2005 (after death of two teenagers fleeing police), lasting 7 nights. 45,000 police deployed; 10,000 arrested. €1 billion in damage. 5,500 vehicles burned. Officer convicted of voluntary homicide. Exposed deep fractures in French society around policing, race, and integration failure.",
      date: "2023-06-27", source: "French Interior Ministry, Le Monde",
      isVerified: true, tags: ["France", "Police", "Riots", "Social Unrest", "Race"],
    },
  ]).returning();

  console.log(`Seeded ${mediaEvents.length} media events`);
  console.log("✅ Extended seed complete!");
}

seedExtended().catch(console.error).finally(() => process.exit(0));
