import { db, militaryActivitiesTable } from "./index";

async function seedMilitary() {
  console.log("Seeding military activities...");

  await db.delete(militaryActivitiesTable);

  await db.insert(militaryActivitiesTable).values([
    {
      title: "Operation Baltic Shield — NATO Enhanced Forward Presence",
      type: "deployment",
      status: "active",
      threatLevel: "high",
      country: "NATO/Multinational",
      countryCode: "NATO",
      flagEmoji: "🛡",
      region: "Eastern Europe",
      location: "Estonia, Latvia, Lithuania, Poland",
      lat: 56.9,
      lng: 24.1,
      involvedCountries: ["United States", "United Kingdom", "Germany", "Canada", "France", "Poland"],
      forces: "4 Multinational Battle Groups",
      assets: ["M1 Abrams MBTs", "Challenger 2 tanks", "Leopard 2A7", "F-35A detachment", "Patriot PAC-3 batteries", "HIMARS"],
      estimatedPersonnel: "~18,000",
      objective: "Deterrence and collective defense of NATO eastern flank against Russian aggression",
      description: "NATO's Enhanced Forward Presence (eFP) has been reinforced to battalion-plus strength at all four battle groups. Following Russia's continued offensive in Ukraine, SACEUR authorized additional air defense assets and pre-positioned armor. US 2nd Cavalry Regiment rotates through Poland on a permanent basis.",
      isNatoRelated: true,
      isJoint: true,
      startDate: "2022-03-01",
      endDate: null,
      isOngoing: true,
      updates: [
        "Mar 2026: Additional Patriot battery deployed to Ämari Air Base, Estonia",
        "Feb 2026: US F-16 detachment rotated to Łask Air Base, Poland",
        "Jan 2026: UK reinforced its battle group with additional Challenger 2 tanks",
      ],
    },
    {
      title: "PLA Exercise EASTERN THUNDER — Taiwan Strait",
      type: "exercise",
      status: "active",
      threatLevel: "critical",
      country: "China",
      countryCode: "CN",
      flagEmoji: "🇨🇳",
      region: "East Asia",
      location: "Taiwan Strait / ADIZ",
      lat: 24.5,
      lng: 122.0,
      involvedCountries: ["China"],
      forces: "PLA Eastern Theater Command",
      assets: ["J-20 stealth fighters", "DF-17 hypersonic missiles", "Type 055 destroyers", "Type 093 submarines", "H-6K bombers", "PHL-03 MLRS"],
      estimatedPersonnel: "~45,000",
      objective: "Simulated joint island-seizure operation and blockade enforcement scenario targeting Taiwan",
      description: "PLA Eastern Theater Command is conducting its largest exercise since August 2022. Includes live-fire drills, amphibious landing rehearsals, and blockade simulation. Exercise CAUTION: Multiple ROCAF scrambles recorded. USN CSG-11 repositioned to 200nm east of Taiwan. Taiwan has raised readiness to Level 2.",
      isNatoRelated: false,
      isJoint: false,
      startDate: "2026-04-05",
      endDate: "2026-04-18",
      isOngoing: true,
      updates: [
        "Apr 10 2026: PLA aircraft crossed median line 46 times in 24 hours — record high",
        "Apr 09 2026: PLAN Type 055 destroyer entered Taiwan ADIZ",
        "Apr 08 2026: Live-fire missile drill in waters SE of Taiwan — 4 DF-11B missiles fired",
        "Apr 07 2026: Exercise commenced with naval encirclement of Taiwan",
      ],
    },
    {
      title: "RESTRICTED AIRSPACE — R-6912 Black Sea Operations Zone",
      type: "restricted_airspace",
      status: "active",
      threatLevel: "high",
      country: "Russia",
      countryCode: "RU",
      flagEmoji: "🇷🇺",
      region: "Eastern Europe",
      location: "Black Sea / Crimea Peninsula",
      lat: 44.9,
      lng: 34.1,
      involvedCountries: ["Russia", "Ukraine"],
      forces: "Russian Aerospace Forces / BSF",
      assets: ["S-400 SAM systems", "Su-35S fighters", "Tu-22M3 bombers", "Kh-22 cruise missiles"],
      estimatedPersonnel: null,
      objective: "Enforce exclusion zone around Crimea and Black Sea fleet operations; deny ISR access",
      description: "Russia maintains a permanent military exclusion zone over Crimea and surrounding Black Sea waters. NOTAM R-6912 restricts all civil aviation below FL200 within 50nm of Crimea. Active S-400 systems provide SAM coverage extending to 400km. Multiple NATO ISR aircraft have been shadowed by Su-35S intercepts.",
      isNatoRelated: false,
      isJoint: false,
      startDate: "2022-02-24",
      endDate: null,
      isOngoing: true,
      updates: [
        "Apr 2026: Extended zone boundary 20nm south following Ukrainian drone strike attempt",
        "Mar 2026: Turkish commercial flights rerouted; ICAO raised incident flag",
        "Feb 2026: RC-135V Rivet Joint intercepted at zone boundary by Su-35S",
      ],
    },
    {
      title: "USN CSG-11 Carl Vinson — Western Pacific Patrol",
      type: "naval_patrol",
      status: "active",
      threatLevel: "medium",
      country: "United States",
      countryCode: "US",
      flagEmoji: "🇺🇸",
      region: "East Asia",
      location: "Western Pacific / South China Sea",
      lat: 15.2,
      lng: 116.8,
      involvedCountries: ["United States", "Japan", "Australia"],
      forces: "Carrier Strike Group 11",
      assets: ["USS Carl Vinson (CVN-70)", "F/A-18E/F Super Hornets", "F-35C", "Ticonderoga-class cruiser", "Arleigh Burke DDGs x4", "Virginia-class SSN"],
      estimatedPersonnel: "~7,500",
      objective: "Freedom of Navigation / Power Projection / Allied reassurance in response to PLA exercise",
      description: "CSG-11 repositioned from routine patrol to the Philippine Sea in response to PLA EASTERN THUNDER exercise. Operating in coordination with JMSDF helicopter destroyer group. Multiple FONOPS conducted within 12nm of Chinese-claimed artificial islands in Spratly chain. PLAN shadowed continuously by Type 055.",
      isNatoRelated: false,
      isJoint: true,
      startDate: "2026-03-15",
      endDate: null,
      isOngoing: true,
      updates: [
        "Apr 10 2026: CSG-11 repositioned 200nm east of Taiwan — elevated readiness posture",
        "Apr 07 2026: Joint exercise with JMSDF in Philippine Sea",
        "Apr 01 2026: FONOP through South China Sea Spratly Islands",
      ],
    },
    {
      title: "NO-FLY ZONE — Sudan (SAF/RSF Conflict Zone)",
      type: "no_fly_zone",
      status: "active",
      threatLevel: "high",
      country: "Sudan",
      countryCode: "SD",
      flagEmoji: "🇸🇩",
      region: "Sub-Saharan Africa",
      location: "Khartoum / Darfur Region",
      lat: 15.5,
      lng: 32.5,
      involvedCountries: ["Sudan", "Russia", "UAE", "Egypt"],
      forces: "Sudanese Armed Forces / RSF Paramilitary",
      assets: ["Su-25 ground attack aircraft", "Mi-24 Hind gunships", "L-39 Albatros", "armed drones (CAIG Wing Loong)"],
      estimatedPersonnel: null,
      objective: "Contested airspace — SAF conducting offensive CAS missions against RSF positions in Khartoum and El Fasher",
      description: "Sudanese Armed Forces control airspace over Khartoum and major urban centers following extended civil war. SAF conducting daily CAS sorties against RSF strongholds. UN Security Council resolutions on NFZ blocked by Russian and Chinese vetoes. UAE-supplied Wing Loong drones operating on behalf of RSF detected. ICAO declared airspace UNSAFE — NOTAM A1247/26.",
      isNatoRelated: false,
      isJoint: false,
      startDate: "2023-04-15",
      endDate: null,
      isOngoing: true,
      updates: [
        "Apr 2026: SAF airstrike on RSF-held El Fasher market — 34 civilian casualties reported",
        "Mar 2026: RSF MANPADS downed SAF Mi-17 near Nyala",
        "Feb 2026: UAE-linked Wing Loong drone crash in South Darfur — markings removed",
      ],
    },
    {
      title: "Exercise IRON ANVIL — US-ROK Combined Forces",
      type: "exercise",
      status: "active",
      threatLevel: "medium",
      country: "United States",
      countryCode: "US",
      flagEmoji: "🇺🇸",
      region: "East Asia",
      location: "Korean Peninsula / Yellow Sea",
      lat: 37.5,
      lng: 127.0,
      involvedCountries: ["United States", "South Korea"],
      forces: "US Forces Korea / ROK Joint Chiefs",
      assets: ["F-35B STOVL", "B-52H strategic bombers", "Ohio-class SSBN visit", "K2 Black Panther MBTs", "Patriot PAC-3 MSE", "THAAD battery"],
      estimatedPersonnel: "~16,000",
      objective: "Annual readiness exercise simulating DPRK conventional + WMD contingency response; extended deterrence demonstration",
      description: "Exercise IRON ANVIL represents the largest combined exercise since 2017. Explicitly designed to demonstrate extended deterrence following DPRK ICBM tests. First B-52H strategic bomber involvement in 3 years; Ohio-class SSBN port call to Busan publicized as deterrence signal. DPRK responded with short-range ballistic missile salvo into East Sea.",
      isNatoRelated: false,
      isJoint: true,
      startDate: "2026-04-01",
      endDate: "2026-04-21",
      isOngoing: true,
      updates: [
        "Apr 10 2026: DPRK fired 4x KN-23 SRBMs in response — landed in DPRK EEZ",
        "Apr 08 2026: B-52H flew within 50nm of DPRK border — KPA on maximum readiness",
        "Apr 05 2026: Ohio-class SSBN USS Kentucky arrived Busan — publicized deterrence signal",
        "Apr 01 2026: Exercise commenced — DPRK declared 'grave provocation'",
      ],
    },
    {
      title: "RESTRICTED AIRSPACE — Ukraine Active Conflict Zone",
      type: "restricted_airspace",
      status: "active",
      threatLevel: "critical",
      country: "Russia / Ukraine",
      countryCode: "UA",
      flagEmoji: "🇺🇦",
      region: "Eastern Europe",
      location: "Eastern Ukraine / Frontline",
      lat: 48.4,
      lng: 37.5,
      involvedCountries: ["Ukraine", "Russia"],
      forces: "Russian Aerospace Forces / Ukrainian Air Force",
      assets: ["Su-35S", "Su-34", "MiG-31K Foxhound", "Kinzhal hypersonic", "F-16AM (Ukraine)", "Patriot PAC-3 (Ukraine)", "S-300 batteries"],
      estimatedPersonnel: null,
      objective: "Active contested airspace — both sides conducting offensive/defensive air operations",
      description: "Entire Ukrainian airspace is classified DANGER — EUROCONTROL NOTAM A0734/22 remains in force. Russian Aerospace Forces conducting strategic bombing raids using Tu-95MS cruise missile launches. Ukrainian Air Force flying F-16 combat missions with Dutch/Danish pilots. Russian Su-34 conducting glide bomb (FAB-3000) strikes. ISR: NATO AWACS maintaining patrol over Poland.",
      isNatoRelated: false,
      isJoint: false,
      startDate: "2022-02-24",
      endDate: null,
      isOngoing: true,
      updates: [
        "Apr 10 2026: Russian Tu-95MS launched 14x Kh-101 cruise missiles targeting energy grid",
        "Apr 09 2026: Ukrainian F-16 intercepted 3 Shahed-136 drones over Kyiv oblast",
        "Apr 08 2026: FAB-3000 glide bomb strike destroyed Kharkiv rail junction",
      ],
    },
    {
      title: "Exercise NOBLE JUMP 2026 — NATO VJTF Deployment",
      type: "exercise",
      status: "active",
      threatLevel: "low",
      country: "NATO/Multinational",
      countryCode: "NATO",
      flagEmoji: "🛡",
      region: "Eastern Europe",
      location: "Romania / Bulgaria",
      lat: 44.4,
      lng: 26.1,
      involvedCountries: ["Germany", "Netherlands", "Czech Republic", "Romania", "Spain"],
      forces: "NATO Very High Readiness Joint Task Force",
      assets: ["CH-47F Chinooks", "NH90 helicopters", "CV9040 IFVs", "SHORAD systems"],
      estimatedPersonnel: "~5,000",
      objective: "Validate VJTF deployment capability within 5-day timeline requirement for Article 5 scenarios",
      description: "Annual NATO certification exercise for the Very High Readiness Joint Task Force (VJTF). Germany leads the VJTF for 2026. Exercise validates the ability to deploy 5,000 personnel within 5 days to any NATO territory. Focus area: southeastern flank vulnerability assessment and Black Sea access security.",
      isNatoRelated: true,
      isJoint: true,
      startDate: "2026-04-08",
      endDate: "2026-04-20",
      isOngoing: true,
      updates: [
        "Apr 09 2026: VJTF achieved full deployment in 4.8 days — within NATO benchmark",
        "Apr 08 2026: Exercise commenced with airlift of lead elements from Bundeswehr",
      ],
    },
    {
      title: "TROOP MOVEMENT — Russian 58th Combined Arms Army (Caucasus)",
      type: "troop_movement",
      status: "active",
      threatLevel: "high",
      country: "Russia",
      countryCode: "RU",
      flagEmoji: "🇷🇺",
      region: "Caucasus",
      location: "Vladikavkaz / Georgia Border",
      lat: 43.0,
      lng: 44.7,
      involvedCountries: ["Russia", "Georgia"],
      forces: "58th Combined Arms Army, Southern Military District",
      assets: ["T-90M tanks", "BMP-3 IFVs", "Tornado-S MLRS", "S-300V4 SAM"],
      estimatedPersonnel: "~12,000 (reduced from Ukraine rotation)",
      objective: "Repositioning of elements from Ukraine theater — assessed as reconstitution; potential South Caucasus deterrence posturing",
      description: "Satellite imagery confirms significant Russian military vehicle movement near Vladikavkaz. Elements from the depleted 58th CAA rotating back from Ukraine for reconstitution. Georgian intelligence assessing whether this represents threat signal related to Abkhazia or South Ossetia. Assessment: MEDIUM CONFIDENCE — reconstitution more likely than offensive preparation.",
      isNatoRelated: false,
      isJoint: false,
      startDate: "2026-03-28",
      endDate: null,
      isOngoing: true,
      updates: [
        "Apr 10 2026: Additional rail shipments detected — estimated 40x T-90M on flatbeds",
        "Apr 05 2026: US NRO satellite pass confirms 3 battalion tactical groups repositioning",
        "Mar 28 2026: Initial reports from open-source OSINT — vehicle columns near Beslan",
      ],
    },
    {
      title: "BASE ACTIVATION — Diego Garcia USAF Strategic Bomber Surge",
      type: "base_activation",
      status: "active",
      threatLevel: "medium",
      country: "United States",
      countryCode: "US",
      flagEmoji: "🇺🇸",
      region: "Indian Ocean",
      location: "Diego Garcia, British Indian Ocean Territory",
      lat: -7.3,
      lng: 72.4,
      involvedCountries: ["United States", "United Kingdom"],
      forces: "USAF Global Strike Command / 2nd Bomb Wing",
      assets: ["B-52H Stratofortress x6", "B-2 Spirit stealth bomber x2", "KC-135 Stratotanker x8", "RQ-4 Global Hawk x2"],
      estimatedPersonnel: "~1,800 surge personnel",
      objective: "Strategic deterrence surge — forward positioning of nuclear-capable bombers in Indo-Pacific for extended deterrence signaling",
      description: "USAF Global Strike Command surged Diego Garcia to maximum operational tempo. Six B-52H and two B-2 stealth bombers now forward-deployed in what PACOM describes as 'routine deterrence posturing.' Timing coincides with PLA EASTERN THUNDER exercise and DPRK ICBM tests. UK has coordinated access rights for USAF operations. KC-135 tanker surge enables deep-penetration mission profiles.",
      isNatoRelated: false,
      isJoint: false,
      startDate: "2026-04-06",
      endDate: null,
      isOngoing: true,
      updates: [
        "Apr 10 2026: B-2 conducted non-stop 36-hour training sortie — route classified",
        "Apr 08 2026: B-52H flew within range of PLA exercise zone — PLAAF scrambled J-20",
        "Apr 06 2026: Surge deployment confirmed by Pentagon — 'routine deterrence posture'",
      ],
    },
    {
      title: "IDF Northern Command — Lebanon Border Reinforcement",
      type: "deployment",
      status: "active",
      threatLevel: "high",
      country: "Israel",
      countryCode: "IL",
      flagEmoji: "🇮🇱",
      region: "Middle East",
      location: "Northern Israel / Lebanon Border",
      lat: 33.1,
      lng: 35.5,
      involvedCountries: ["Israel", "Lebanon", "Hezbollah"],
      forces: "IDF Northern Command / 210th Division",
      assets: ["Merkava IV tanks", "Namer AFVs", "Iron Dome batteries x6", "David's Sling battery", "F-35I Adir", "AH-64D Apaches"],
      estimatedPersonnel: "~35,000",
      objective: "Deterrence and defense of northern border; counter-Hezbollah posture following Lebanon ceasefire fragility",
      description: "IDF has maintained elevated force posture on the Lebanese border since November 2024 ceasefire. Multiple Hezbollah rocket launch attempts intercepted by Iron Dome. IDF conducting limited cross-border operations under the Law of Pursuit. Hezbollah rebuilding weapons stockpiles with IRGC support via Syria corridor. Netanyahu approved limited strike authority on Hezbollah re-armament convoys.",
      isNatoRelated: false,
      isJoint: false,
      startDate: "2024-11-27",
      endDate: null,
      isOngoing: true,
      updates: [
        "Apr 10 2026: IDF air strike on Hezbollah weapons depot near Baalbek — 3 fighters killed",
        "Apr 09 2026: Iron Dome intercepts 7 Katyusha rockets from southern Lebanon",
        "Apr 07 2026: IDF armored elements redeployed from Gaza to northern command",
      ],
    },
    {
      title: "Exercise SEA DRAGON 2026 — US-Japan-Australia Anti-Submarine",
      type: "exercise",
      status: "active",
      threatLevel: "low",
      country: "United States",
      countryCode: "US",
      flagEmoji: "🇺🇸",
      region: "Pacific",
      location: "Mariana Islands / Guam Waters",
      lat: 15.0,
      lng: 145.7,
      involvedCountries: ["United States", "Japan", "Australia", "Canada", "India"],
      forces: "P-8A Poseidon multi-mission squadrons",
      assets: ["P-8A Poseidon x12", "MH-60R Seahawk", "USS John C. Stennis SSN", "JS Izumo (DDH-183)", "HMAS Canberra"],
      estimatedPersonnel: "~3,200",
      objective: "Multinational anti-submarine warfare exercise targeting PLAN submarine threat in Western Pacific",
      description: "Annual multilateral ASW exercise now in its 7th year. Focus has shifted to counter-PLAN submarine operations following detection of PLAN Type 093B SSN operating near Guam. Exercise integrates advanced AI sonar processing from DARPA's POSEIDON program. India participating as observer with P-8I aircraft — first full integration into exercise.",
      isNatoRelated: false,
      isJoint: true,
      startDate: "2026-04-07",
      endDate: "2026-04-19",
      isOngoing: true,
      updates: [
        "Apr 09 2026: P-8A detected and tracked PLAN submarine for 14 hours — classified report filed",
        "Apr 07 2026: Exercise commenced — India P-8I integrated for first time",
      ],
    },
    {
      title: "NAVAL PATROL — PLAN South Sea Fleet, South China Sea",
      type: "naval_patrol",
      status: "active",
      threatLevel: "high",
      country: "China",
      countryCode: "CN",
      flagEmoji: "🇨🇳",
      region: "Southeast Asia",
      location: "South China Sea / Nine-Dash Line",
      lat: 11.0,
      lng: 114.0,
      involvedCountries: ["China", "Philippines", "Vietnam", "Malaysia"],
      forces: "PLAN South Sea Fleet",
      assets: ["Type 075 LHD", "Type 052D destroyers x3", "Coast Guard vessels x8", "maritime militia fishing boats"],
      estimatedPersonnel: "~4,000",
      objective: "Assertion of Nine-Dash Line sovereignty claims; harassing Philippines resupply missions to BRP Sierra Madre",
      description: "PLAN South Sea Fleet maintaining continuous patrol of South China Sea disputed features. China Coast Guard (CCG) vessels using water cannons against Philippine resupply vessels headed to BRP Sierra Madre at Second Thomas Shoal. Type 075 LHD (amphibious assault ship) operating near Paracel Islands in show of force. Philippines has lodged 8 diplomatic protests in April 2026.",
      isNatoRelated: false,
      isJoint: false,
      startDate: "2026-01-01",
      endDate: null,
      isOngoing: true,
      updates: [
        "Apr 10 2026: CCG vessel fired water cannon at Philippine Coast Guard escort — injuries reported",
        "Apr 08 2026: PLAN Type 075 LHD conducted amphibious drill near Paracel Islands",
        "Apr 06 2026: Philippines activated US-PHL Mutual Defense Treaty consultations",
      ],
    },
    {
      title: "BASE ACTIVATION — RAF Akrotiri Cyprus, Middle East Alert",
      type: "base_activation",
      status: "active",
      threatLevel: "medium",
      country: "United Kingdom",
      countryCode: "GB",
      flagEmoji: "🇬🇧",
      region: "Middle East",
      location: "RAF Akrotiri, Cyprus",
      lat: 34.6,
      lng: 32.9,
      involvedCountries: ["United Kingdom", "United States"],
      forces: "RAF No. 903 Expeditionary Air Wing",
      assets: ["Typhoon FGR4 x6", "Sentinel R1 ISR", "Voyager KC2 tanker", "RC-135W Rivet Joint"],
      estimatedPersonnel: "~1,200 additional surge",
      objective: "ISR and strike readiness surge for potential Iran contingency; Red Sea maritime security support",
      description: "RAF Akrotiri surged to elevated readiness following Iranian IRGC threats to UK shipping in the Gulf. Typhoon FGR4 aircraft conducting daily ISR patrols over Red Sea corridor. RC-135W Rivet Joint signals intelligence flights increased from 3 to 7 per week. Coordination with USS Dwight D. Eisenhower CSG in Red Sea.",
      isNatoRelated: false,
      isJoint: true,
      startDate: "2026-02-14",
      endDate: null,
      isOngoing: true,
      updates: [
        "Apr 09 2026: Typhoon FGR4 escorted RAF Sentinel over Strait of Hormuz — IRIAF intercept attempt",
        "Apr 05 2026: Additional Voyager tanker deployed — extends Typhoon loiter time over Gulf",
      ],
    },
  ]);

  console.log("✅ Military activities seeded!");
  process.exit(0);
}

seedMilitary().catch(e => { console.error(e); process.exit(1); });
