import { db, cyberIncidentsTable, aptGroupsTable, nuclearProgramsTable, operationsTimelineTable } from "./index";

async function seed2026() {
  console.log("Seeding 2026 extended intelligence data...");

  await db.delete(cyberIncidentsTable);
  await db.delete(aptGroupsTable);
  await db.delete(nuclearProgramsTable);
  await db.delete(operationsTimelineTable);

  await db.insert(aptGroupsTable).values([
    {
      name: "APT40",
      aliases: ["BRONZE MOHAWK", "Kryptonite Panda", "TEMP.Periscope"],
      attribution: "China",
      country: "China",
      active: "yes",
      sophistication: "nation-state",
      primaryTargets: ["Maritime", "Defense", "Aviation", "Research"],
      knownTtps: ["Spearphishing", "Zero-day exploits", "Living off the land", "Supply chain compromise"],
      notableOperations: ["SolarWinds supply chain (adjacent)", "Maritime sector espionage 2024", "Pacific defense contractor breach 2025"],
      firstSeen: "2013-01-01",
      description: "PRC-sponsored APT linked to Hainan State Security Department. Heavily focused on maritime and South China Sea intelligence collection.",
    },
    {
      name: "Lazarus Group",
      aliases: ["Hidden Cobra", "ZINC", "Guardians of Peace"],
      attribution: "North Korea",
      country: "North Korea",
      active: "yes",
      sophistication: "nation-state",
      primaryTargets: ["Financial", "Crypto", "Defense", "Aerospace"],
      knownTtps: ["Crypto theft", "SWIFT attacks", "Watering hole", "Backdoor deployment"],
      notableOperations: ["$3.8B crypto theft 2025", "Aerospace contractor breach Q1 2026", "Bybit exchange hack Feb 2025"],
      firstSeen: "2009-01-01",
      description: "DPRK's primary cyber warfare unit operating under RGB. Primary mission: sanctions evasion through cryptocurrency theft and defense intelligence collection.",
    },
    {
      name: "Sandworm",
      aliases: ["VOODOO BEAR", "ELECTRUM", "Telebots"],
      attribution: "Russia",
      country: "Russia",
      active: "yes",
      sophistication: "nation-state",
      primaryTargets: ["Critical Infrastructure", "Energy", "Government", "Ukraine"],
      knownTtps: ["Destructive wiper malware", "ICS attacks", "Supply chain", "Spearphishing"],
      notableOperations: ["Ukrainian power grid attacks (ongoing)", "NotPetya 2017", "Ukrainian railway disruption 2025", "EU energy grid probing 2026"],
      firstSeen: "2009-01-01",
      description: "GRU Unit 74455. Russia's most aggressive cyber unit, responsible for destructive attacks on Ukrainian critical infrastructure as part of the ongoing conflict.",
    },
    {
      name: "APT28",
      aliases: ["Fancy Bear", "STRONTIUM", "Sofacy", "GRU Unit 26165"],
      attribution: "Russia",
      country: "Russia",
      active: "yes",
      sophistication: "nation-state",
      primaryTargets: ["Government", "Military", "Elections", "NATO members"],
      knownTtps: ["Credential phishing", "Zero-day (Outlook, WinRAR)", "LOLBIN", "Influence operations"],
      notableOperations: ["DNC hack 2016", "German Bundestag 2024-2025", "Polish election interference 2025", "NATO member exfiltration 2026"],
      firstSeen: "2004-01-01",
      description: "Russia's GRU military intelligence unit specializing in political espionage and election interference across NATO member states.",
    },
    {
      name: "MuddyWater",
      aliases: ["Static Kitten", "Seedworm", "MERCURY"],
      attribution: "Iran",
      country: "Iran",
      active: "yes",
      sophistication: "advanced",
      primaryTargets: ["Telecom", "Government", "Defense", "Middle East"],
      knownTtps: ["Spearphishing", "PowerShell abuse", "RAT deployment", "Living off the land"],
      notableOperations: ["Israeli telecom breach 2025", "Saudi government espionage 2024", "Gulf state infrastructure probing 2026"],
      firstSeen: "2017-01-01",
      description: "Iranian MOIS-linked APT conducting regional espionage, with activity surging in 2025-2026 amid tensions with Israel and Gulf states.",
    },
    {
      name: "Volt Typhoon",
      aliases: ["BRONZE SILHOUETTE", "Vanguard Panda"],
      attribution: "China",
      country: "China",
      active: "yes",
      sophistication: "nation-state",
      primaryTargets: ["US Critical Infrastructure", "Military", "Telecom", "Energy"],
      knownTtps: ["Living off the land (LOTL)", "Pre-positioning", "SOHO router compromise", "Stealth persistence"],
      notableOperations: ["US critical infrastructure pre-positioning (ongoing)", "Guam military network access 2023-2025", "Pacific undersea cable reconnaissance 2026"],
      firstSeen: "2021-01-01",
      description: "PRC APT pre-positioning in US critical infrastructure for potential conflict scenarios. NSA/CISA issued emergency directive Jan 2026.",
    },
    {
      name: "Salt Typhoon",
      aliases: ["GhostEmperor", "FamousSparrow"],
      attribution: "China",
      country: "China",
      active: "yes",
      sophistication: "nation-state",
      primaryTargets: ["US Telecoms", "Wiretap infrastructure", "ISPs"],
      knownTtps: ["Telecom backbone compromise", "Lawful intercept exploitation", "Zero-days"],
      notableOperations: ["AT&T/Verizon/T-Mobile breach 2024-2025 (ongoing)", "US lawful intercept system compromise", "9 major telcos breached"],
      firstSeen: "2020-01-01",
      description: "PRC APT that breached major US telecommunications providers in 2024, accessing lawful intercept systems used by US law enforcement. Ongoing remediation in 2026.",
    },
  ]);
  console.log("Seeded APT groups");

  await db.insert(cyberIncidentsTable).values([
    {
      title: "Volt Typhoon: US Critical Infrastructure Pre-Positioning",
      description: "PRC-attributed Volt Typhoon has maintained persistent access across US water utilities, power grids, and transportation networks. NSA issued emergency directive in January 2026 after discovering dormant backdoors in 23 utility providers.",
      attackType: "APT / Pre-positioning",
      threatActor: "Volt Typhoon",
      attribution: "China",
      targetSector: "Critical Infrastructure",
      targetCountry: "United States",
      originCountry: "China",
      severity: "critical",
      status: "active",
      iocs: ["SOHO router compromise", "LOTL techniques", "Modified Cisco IOS"],
      ttps: ["T1078 Valid Accounts", "T1105 Ingress Tool Transfer", "T1571 Non-Standard Port"],
      financialDamage: "N/A (intelligence operation)",
      detectedDate: "2025-11-14",
    },
    {
      title: "Lazarus Group: Bybit Cryptocurrency Exchange Hack",
      description: "North Korea's Lazarus Group executed the largest cryptocurrency theft in history, stealing $1.46 billion from Bybit exchange in February 2025. Funds routed through mixing services to fund DPRK missile program.",
      attackType: "Financial / Crypto Theft",
      threatActor: "Lazarus Group",
      attribution: "North Korea",
      targetSector: "Financial / Cryptocurrency",
      targetCountry: "United Arab Emirates",
      originCountry: "North Korea",
      severity: "critical",
      status: "resolved",
      iocs: ["Compromised Safe{Wallet} transaction", "North Korean IP ranges"],
      ttps: ["T1566 Phishing", "T1055 Process Injection", "T1041 Exfiltration Over C2"],
      financialDamage: "$1.46 billion USD",
      detectedDate: "2025-02-21",
      resolvedDate: "2025-03-10",
    },
    {
      title: "Salt Typhoon: US Telecom Backbone Compromise",
      description: "PRC-linked Salt Typhoon breached 9 major US telecommunications providers, accessing lawful intercept systems. Calls of senior US government officials including presidential campaigns were intercepted. Remediation ongoing into 2026.",
      attackType: "Espionage / Network Intrusion",
      threatActor: "Salt Typhoon",
      attribution: "China",
      targetSector: "Telecommunications",
      targetCountry: "United States",
      originCountry: "China",
      severity: "critical",
      status: "active",
      iocs: ["Cisco IOS XE exploit", "Compromised CALEA systems"],
      ttps: ["T1190 Exploit Public-Facing Application", "T1557 Adversary-in-the-Middle", "T1119 Automated Collection"],
      financialDamage: "N/A (intelligence operation)",
      detectedDate: "2024-10-05",
    },
    {
      title: "Sandworm: Ukrainian Railway Network Attack",
      description: "GRU Sandworm disrupted Ukraine's railway scheduling systems in Q4 2025, delaying troop and supply movements during critical winter offensive period. Wiper malware deployed on operational technology systems.",
      attackType: "Destructive / Wiper",
      threatActor: "Sandworm",
      attribution: "Russia",
      targetSector: "Transportation / Military Logistics",
      targetCountry: "Ukraine",
      originCountry: "Russia",
      severity: "high",
      status: "resolved",
      iocs: ["CaddyWiper variant", "INDUSTROYER2 deployment"],
      ttps: ["T1485 Data Destruction", "T1486 Data Encrypted for Impact"],
      detectedDate: "2025-11-08",
      resolvedDate: "2025-11-22",
    },
    {
      title: "APT40: Pacific Defense Contractor Data Exfiltration",
      description: "Chinese APT40 exfiltrated classified submarine propulsion design data from Australian and US defense contractors in an 8-month operation discovered in March 2026. Linked to AUKUS submarine program intelligence collection.",
      attackType: "Espionage / Data Exfiltration",
      threatActor: "APT40",
      attribution: "China",
      targetSector: "Defense / Maritime",
      targetCountry: "Australia",
      originCountry: "China",
      severity: "critical",
      status: "active",
      iocs: ["KEYPLUG backdoor", "WebShell on internet-facing systems"],
      ttps: ["T1190 Exploit Public-Facing Application", "T1560 Archive Collected Data"],
      financialDamage: "Classified program data loss",
      detectedDate: "2026-03-12",
    },
    {
      title: "Iranian Cyber Army: Israeli Infrastructure Campaign",
      description: "MuddyWater-linked actors conducted sustained campaign against Israeli telecom and energy infrastructure. Coordinated with Hezbollah rocket campaign as cyber-kinetic hybrid operation.",
      attackType: "Hybrid Cyber-Kinetic",
      threatActor: "MuddyWater",
      attribution: "Iran",
      targetSector: "Telecommunications / Energy",
      targetCountry: "Israel",
      originCountry: "Iran",
      severity: "high",
      status: "resolved",
      iocs: ["POWERSTATS backdoor", "Iranian C2 infrastructure"],
      ttps: ["T1566.001 Spearphishing Attachment", "T1053 Scheduled Task"],
      detectedDate: "2025-08-14",
      resolvedDate: "2025-10-02",
    },
    {
      title: "APT28: German Bundestag Espionage Campaign",
      description: "Russian GRU APT28 conducted sustained espionage against German Bundestag members and defense ministry officials ahead of February 2025 German elections. Voter data and communication exfiltrated.",
      attackType: "Espionage / Election Interference",
      threatActor: "APT28",
      attribution: "Russia",
      targetSector: "Government / Elections",
      targetCountry: "Germany",
      originCountry: "Russia",
      severity: "high",
      status: "resolved",
      iocs: ["Fancy Bear phishing domains", "HeadLace malware"],
      ttps: ["T1566 Phishing", "T1114 Email Collection"],
      detectedDate: "2024-12-03",
      resolvedDate: "2025-01-28",
    },
    {
      title: "Ransomware: Global Healthcare Sector Wave",
      description: "Coordinated ransomware wave (LockBit 4.0, BlackCat successor) targeted 200+ hospitals across US, EU, and Australia in Q1 2026. Patient record encryption halted critical care operations for up to 3 weeks.",
      attackType: "Ransomware",
      threatActor: "LockBit 4.0 / Scattered Spider",
      attribution: "Russia / Criminal",
      targetSector: "Healthcare",
      targetCountry: "United States",
      originCountry: "Russia",
      severity: "high",
      status: "active",
      financialDamage: "$890 million USD (aggregate)",
      detectedDate: "2026-01-15",
    },
  ]);
  console.log("Seeded cyber incidents");

  await db.insert(nuclearProgramsTable).values([
    {
      country: "United States",
      countryCode: "US",
      flagEmoji: "🇺🇸",
      programStatus: "confirmed",
      nuclearWarheads: 5550,
      deliveryCapability: ["ICBM (Minuteman III)", "SLBM (Trident II)", "B-2 Spirit", "B-21 Raider", "F-35A DCA"],
      programType: ["Strategic", "Tactical", "SSBN Fleet"],
      treatyStatus: ["New START (expired 2026)", "NPT signatory", "CTBT signatory"],
      latestTest: "1992 (moratorium)",
      threatLevel: "low",
      iaeaCompliance: "full",
      estimatedRange: 13000,
      description: "World's largest nuclear arsenal by capability. B-21 Raider entered service 2023. Nuclear Posture Review 2024 emphasized modernization. New START expired Feb 2026 with no successor agreement.",
      recentDevelopments: ["B-21 Raider IOC declared 2025", "New START expired Feb 2026", "W93 warhead development ongoing", "Sea-launched cruise missile program restarted"],
    },
    {
      country: "Russia",
      countryCode: "RU",
      flagEmoji: "🇷🇺",
      programStatus: "confirmed",
      nuclearWarheads: 6257,
      deliveryCapability: ["RS-28 Sarmat (Satan-2)", "Avangard HGV", "Poseidon UUV", "Kinzhal ALBM", "Belgorod SSBN"],
      programType: ["Strategic", "Tactical", "Hypersonic"],
      treatyStatus: ["New START suspended (Feb 2023)", "NPT signatory"],
      latestTest: "1990 (moratorium)",
      threatLevel: "critical",
      iaeaCompliance: "partial",
      estimatedRange: 16000,
      description: "World's largest stockpile. Putin suspended New START participation in 2023. Sarmat ICBM deployed. Poseidon nuclear torpedo under sea trials. Multiple nuclear threats made during Ukraine conflict.",
      recentDevelopments: ["New START participation suspended", "RS-28 Sarmat deployed 2023", "Poseidon UUV sea trials ongoing", "Nuclear doctrine lowered use threshold 2024", "Tactical nuclear exercises near Ukraine border 2025"],
    },
    {
      country: "China",
      countryCode: "CN",
      flagEmoji: "🇨🇳",
      programStatus: "confirmed",
      nuclearWarheads: 500,
      deliveryCapability: ["DF-5B ICBM", "DF-41 ICBM", "JL-3 SLBM", "DF-21D ASBM", "H-6N bomber"],
      programType: ["Strategic", "Expanding tactical"],
      treatyStatus: ["NPT signatory", "CTBT signatory (unratified)"],
      latestTest: "1996 (moratorium)",
      threatLevel: "high",
      iaeaCompliance: "full",
      estimatedRange: 15000,
      description: "Fastest growing arsenal globally. Estimated 500 warheads in 2026, up from 300 in 2020. SIPRI projects 1,000 by 2030. 360 new ICBM silos detected in Xinjiang/Inner Mongolia. No first use policy maintained.",
      recentDevelopments: ["500 warheads reached 2026", "Silo construction at 3 new fields confirmed", "DF-41 MIRV deployment expanding", "JL-3 SLBM on Type 096 SSBN entering service", "Nuclear alert level elevated 2025"],
    },
    {
      country: "North Korea",
      countryCode: "KP",
      flagEmoji: "🇰🇵",
      programStatus: "confirmed",
      nuclearWarheads: 50,
      deliveryCapability: ["Hwasong-17 ICBM", "Hwasong-18 (solid fuel)", "Pukguksong-5 SLBM", "Hypersonic Hwasong-8"],
      programType: ["Strategic", "Tactical", "HGV"],
      treatyStatus: ["Withdrew from NPT 2003", "Non-signatory CTBT"],
      latestTest: "2017 thermonuclear",
      threatLevel: "critical",
      iaeaCompliance: "none",
      estimatedRange: 15000,
      description: "Accelerating program with 40-50 warheads estimated. Hwasong-18 solid-fuel ICBM achieves rapid launch. Multiple ICBM tests 2025-2026. Technical assistance from Russia suspected post-arms deal.",
      recentDevelopments: ["Hwasong-18 solid-fuel ICBM deployed", "3 ICBM tests in 2025-2026", "Russia-DPRK arms agreement includes technology transfer", "7th nuclear test preparation at Punggye-ri suspected", "Tactical nuclear warhead miniaturization claimed"],
    },
    {
      country: "Pakistan",
      countryCode: "PK",
      flagEmoji: "🇵🇰",
      programStatus: "confirmed",
      nuclearWarheads: 170,
      deliveryCapability: ["Shaheen-III MRBM", "Babur cruise missile", "Nasr tactical weapon", "Ra'ad ALCM"],
      programType: ["Strategic", "Tactical"],
      treatyStatus: ["Non-signatory NPT", "Non-signatory CTBT"],
      latestTest: "1998",
      threatLevel: "high",
      iaeaCompliance: "partial",
      estimatedRange: 2750,
      description: "Nuclear-armed state with fastest growing arsenal in South Asia. Tactical Nasr battlefield weapons a key concern. Instability amid political crisis and IMF negotiations. ISI-military control of arsenal questioned.",
      recentDevelopments: ["Shaheen-III range extended to 2750km", "Tactical Nasr warheads expanded", "Political instability (Imran Khan arrest) raised safety concerns", "Chinese technical cooperation ongoing"],
    },
    {
      country: "Iran",
      countryCode: "IR",
      flagEmoji: "🇮🇷",
      programStatus: "developing",
      nuclearWarheads: 0,
      deliveryCapability: ["Shahab-3 MRBM", "Sejil-2", "Emad (precision)"],
      programType: ["Suspected weapons program", "Civilian enrichment (89.9% U-235)"],
      treatyStatus: ["NPT signatory", "JCPOA abandoned 2018"],
      latestTest: "N/A",
      threatLevel: "critical",
      iaeaCompliance: "non-compliant",
      estimatedRange: 2000,
      description: "Iran enriching uranium to 89.9% (weapons-grade threshold 90%). IAEA estimates Iran could produce fissile material for 1 bomb in weeks if decision made. Nuclear deal effectively dead. Breakout capacity reached 2024.",
      recentDevelopments: ["Enrichment to 89.9% U-235 confirmed Jan 2026", "IAEA inspectors expelled from 4 sites", "Underground Fordow facility expanded", "60% enrichment stockpile sufficient for 5 warheads", "Iran-Russia nuclear cooperation MOU signed 2025"],
    },
    {
      country: "Israel",
      countryCode: "IL",
      flagEmoji: "🇮🇱",
      programStatus: "confirmed",
      nuclearWarheads: 90,
      deliveryCapability: ["Jericho-3 ICBM", "Dolphin-class SLCM", "F-35I Adir (DCA)"],
      programType: ["Strategic", "Second strike"],
      treatyStatus: ["Non-signatory NPT", "Ambiguity policy"],
      latestTest: "Suspected (Vela incident 1979)",
      threatLevel: "low",
      iaeaCompliance: "partial",
      estimatedRange: 11500,
      description: "Israel maintains policy of nuclear ambiguity. Estimated 90 warheads. Jericho-3 provides intercontinental range. Dolphin-class submarines provide second-strike capability. Iran's nuclear progress the primary driver for potential breakout.",
      recentDevelopments: ["Jericho-3 extended range test 2024", "Iran breakout concerns accelerating Israeli military planning", "Underground hardening of Negev Nuclear Research Center"],
    },
    {
      country: "India",
      countryCode: "IN",
      flagEmoji: "🇮🇳",
      programStatus: "confirmed",
      nuclearWarheads: 172,
      deliveryCapability: ["Agni-VI ICBM (developing)", "Agni-V ICBM", "Arihant SSBN", "Rafale DCA"],
      programType: ["Strategic", "No-first-use policy"],
      treatyStatus: ["Non-signatory NPT", "CTBT signatory"],
      latestTest: "1998 Pokhran-II",
      threatLevel: "low",
      iaeaCompliance: "partial",
      estimatedRange: 8000,
      description: "Steadily expanding arsenal in response to both Pakistan and China. Agni-VI ICBM under development will target full Chinese mainland. No-first-use policy maintained. SSBN fleet modernizing.",
      recentDevelopments: ["Agni-V MIRV successfully tested 2024", "Agni-VI development ongoing (12,000km+ range)", "INS Arihant patrol capability expanded", "MIRV warhead program advancing"],
    },
  ]);
  console.log("Seeded nuclear programs");

  const now = new Date();
  const hoursAgo = (h: number) => new Date(now.getTime() - h * 60 * 60 * 1000);

  await db.insert(operationsTimelineTable).values([
    {
      title: "North Korea: Hwasong-18 ICBM Launch Detected",
      summary: "NORAD tracking a ballistic missile launch from North Korea's Sunan airbase. Trajectory consistent with Hwasong-18 solid-fuel ICBM. Splashdown detected in Sea of Japan after 75-minute flight.",
      category: "military",
      priority: "critical",
      region: "East Asia",
      countries: ["North Korea", "Japan", "South Korea"],
      source: "NORAD / STRATCOM",
      isAlert: true,
      occurredAt: hoursAgo(2),
    },
    {
      title: "Iran IAEA Update: 89.9% Enrichment Confirmed",
      summary: "IAEA Director General confirms Iran is enriching uranium to 89.9%, one step below weapons-grade (90%). UN Security Council emergency session called. US and Israel hold urgent consultations.",
      category: "nuclear",
      priority: "critical",
      region: "Middle East",
      countries: ["Iran", "Israel", "United States"],
      source: "IAEA",
      isAlert: true,
      occurredAt: hoursAgo(5),
    },
    {
      title: "Russia: Hypersonic Kinzhal Strike on Ukrainian Energy Grid",
      summary: "Russia launched 12 Kinzhal hypersonic missiles targeting Ukrainian power generation facilities in Kharkiv and Zaporizhzhia oblasts. 4 intercepted by Patriot systems. Significant damage to 3 thermal power stations.",
      category: "military",
      priority: "high",
      region: "Eastern Europe",
      countries: ["Russia", "Ukraine"],
      source: "Ukrainian Air Force Command",
      isAlert: false,
      occurredAt: hoursAgo(8),
    },
    {
      title: "China: 7th PLAN Carrier Strike Group Deployment — Taiwan Strait",
      summary: "PLA Navy's Shandong carrier battle group has entered the Taiwan Strait in a new round of exercises. ROC military on heightened alert. US 7th Fleet dispatched USS Theodore Roosevelt CSG.",
      category: "military",
      priority: "critical",
      region: "Asia-Pacific",
      countries: ["China", "Taiwan", "United States"],
      source: "PACOM / ROC MND",
      isAlert: true,
      occurredAt: hoursAgo(12),
    },
    {
      title: "Volt Typhoon: NSA Emergency Directive Issued",
      summary: "NSA issued emergency directive to 23 US utility operators after discovering persistent Volt Typhoon backdoors. President briefed. CISA coordinating emergency remediation. Chinese ambassador summoned.",
      category: "cyber",
      priority: "critical",
      region: "North America",
      countries: ["United States", "China"],
      source: "NSA CISA",
      isAlert: true,
      occurredAt: hoursAgo(18),
    },
    {
      title: "Sudan: RSF Forces Capture Sennar State Capital",
      summary: "Rapid Support Forces have captured Singa, capital of Sennar State, in a rapid advance from El Obeid. SAF air assets striking RSF positions. UN reports 400,000 additional displaced persons in 72 hours.",
      category: "conflict",
      priority: "high",
      region: "Sub-Saharan Africa",
      countries: ["Sudan"],
      source: "ACLED / UN OCHA",
      occurredAt: hoursAgo(24),
    },
    {
      title: "Trump-Putin Call: Ukraine Ceasefire Framework Discussed",
      summary: "White House confirms 90-minute Trump-Putin call. Both sides discuss framework for Ukraine ceasefire. Zelensky not consulted. EU and NATO express deep concern about unilateral negotiations.",
      category: "diplomatic",
      priority: "high",
      region: "Eastern Europe",
      countries: ["United States", "Russia", "Ukraine"],
      source: "White House / Kremlin",
      occurredAt: hoursAgo(30),
    },
    {
      title: "Gaza: Hostage-Ceasefire Negotiations Collapse",
      summary: "Qatar-mediated ceasefire talks collapse after Hamas rejection of Phase 2 terms. IDF announces resumption of targeted operations in Rafah. 8 hostages released in failed deal.",
      category: "conflict",
      priority: "high",
      region: "Middle East",
      countries: ["Israel", "Palestinian Territories", "Qatar"],
      source: "Reuters",
      occurredAt: hoursAgo(36),
    },
    {
      title: "BRICS: New Reserve Currency Framework Adopted",
      summary: "BRICS+ summit in Kazan adopts framework for commodity-backed reserve currency unit. China, Russia, India, Brazil, UAE commit. US Treasury calls move 'economic warfare'. Dollar-denominated oil trade share drops to 68%.",
      category: "economic",
      priority: "medium",
      region: "Global",
      countries: ["China", "Russia", "India", "Brazil"],
      source: "BRICS Secretariat",
      occurredAt: hoursAgo(48),
    },
    {
      title: "Myanmar: Resistance Forces Capture Mandalay Airport",
      summary: "Three Brotherhood Alliance forces capture Mandalay International Airport, Myanmar's second-largest. SAC junta air force conducting retaliatory strikes. 50,000+ civilians evacuating. China calls for ceasefire.",
      category: "conflict",
      priority: "high",
      region: "Southeast Asia",
      countries: ["Myanmar", "China"],
      source: "Irrawaddy Media",
      occurredAt: hoursAgo(60),
    },
    {
      title: "NATO: Article 5 Consultation — Baltic Airspace Violation",
      summary: "NATO calls emergency North Atlantic Council session after Russian military aircraft made 3 incursions into Estonian airspace. F-35 QRA aircraft scrambled. Article 5 consultation invoked per Article 4.",
      category: "military",
      priority: "critical",
      region: "Europe",
      countries: ["Russia", "Estonia", "NATO"],
      source: "NATO HQ Brussels",
      isAlert: true,
      occurredAt: hoursAgo(72),
    },
    {
      title: "IRGC: Hormuz Strait — 3 Commercial Vessels Seized",
      summary: "Iranian IRGC Navy seized 3 oil tankers in the Strait of Hormuz citing 'sanctions violations'. US 5th Fleet deploying additional assets. Lloyd's of London raises war risk premiums 40%.",
      category: "maritime",
      priority: "high",
      region: "Middle East",
      countries: ["Iran", "United States"],
      source: "CENTCOM",
      occurredAt: hoursAgo(84),
    },
    {
      title: "ICJ: New Case Filed — Philippines vs China (South China Sea)",
      summary: "Philippines formally files new case at ICJ over continued Chinese Coast Guard interference with Scarborough Shoal resupply missions. US pledges legal and operational support. China rejects jurisdiction.",
      category: "legal",
      priority: "medium",
      region: "Asia-Pacific",
      countries: ["Philippines", "China"],
      source: "ICJ Registry",
      occurredAt: hoursAgo(96),
    },
    {
      title: "Interpol Silver Notice — North Korean Crypto Laundering Network",
      summary: "Interpol issues Silver Notice targeting 47 individuals across 12 countries linked to Lazarus Group crypto laundering. $380M in Bybit hack proceeds identified in 6 jurisdictions. Extradition requests pending.",
      category: "law-enforcement",
      priority: "medium",
      region: "Global",
      countries: ["North Korea", "UAE", "Singapore"],
      source: "Interpol Lyon",
      occurredAt: hoursAgo(120),
    },
    {
      title: "Venezuela: Opposition Leader Gonzalez Returns — Mass Protests",
      summary: "Exiled opposition leader Edmundo González Urrutia returns to Caracas after 7 months. 800,000+ Venezuelans in streets. Maduro security forces arrest 200+ protesters. Cuba, Russia back Maduro; US recognizes González.",
      category: "political",
      priority: "medium",
      region: "South America",
      countries: ["Venezuela", "United States"],
      source: "Reuters / AP",
      occurredAt: hoursAgo(144),
    },
    {
      title: "US-China Tariff Escalation: 145% on Chinese Imports",
      summary: "Trump administration imposes 145% tariffs on all Chinese imports effective immediately. China retaliates with 125% tariffs on US goods and restricts rare earth exports. Markets drop 4-6%. WTO disputes filed.",
      category: "economic",
      priority: "high",
      region: "Global",
      countries: ["United States", "China"],
      source: "US Trade Representative / Xinhua",
      occurredAt: hoursAgo(168),
    },
  ]);
  console.log("Seeded operations timeline events");

  console.log("✅ 2026 data seeding complete!");
}

seed2026().catch(console.error);
